package org.epay.model.base;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AppCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app
     *
     * @mbg.generated
     */
    protected int limitStart = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app
     *
     * @mbg.generated
     */
    protected int pageSize = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app
     *
     * @mbg.generated
     */
    public AppCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app
     *
     * @mbg.generated
     */
    public void setLimitStart(int limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app
     *
     * @mbg.generated
     */
    public int getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app
     *
     * @mbg.generated
     */
    public void setPageSize(int pageSize) {
        this.pageSize=pageSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app
     *
     * @mbg.generated
     */
    public int getPageSize() {
        return pageSize;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table app
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAppIdIsNull() {
            addCriterion("app_id is null");
            return (Criteria) this;
        }

        public Criteria andAppIdIsNotNull() {
            addCriterion("app_id is not null");
            return (Criteria) this;
        }

        public Criteria andAppIdEqualTo(String value) {
            addCriterion("app_id =", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotEqualTo(String value) {
            addCriterion("app_id <>", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdGreaterThan(String value) {
            addCriterion("app_id >", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdGreaterThanOrEqualTo(String value) {
            addCriterion("app_id >=", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLessThan(String value) {
            addCriterion("app_id <", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLessThanOrEqualTo(String value) {
            addCriterion("app_id <=", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLike(String value) {
            addCriterion("app_id like", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotLike(String value) {
            addCriterion("app_id not like", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdIn(List<String> values) {
            addCriterion("app_id in", values, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotIn(List<String> values) {
            addCriterion("app_id not in", values, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdBetween(String value1, String value2) {
            addCriterion("app_id between", value1, value2, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotBetween(String value1, String value2) {
            addCriterion("app_id not between", value1, value2, "appId");
            return (Criteria) this;
        }

        public Criteria andAppNameIsNull() {
            addCriterion("app_name is null");
            return (Criteria) this;
        }

        public Criteria andAppNameIsNotNull() {
            addCriterion("app_name is not null");
            return (Criteria) this;
        }

        public Criteria andAppNameEqualTo(String value) {
            addCriterion("app_name =", value, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameNotEqualTo(String value) {
            addCriterion("app_name <>", value, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameGreaterThan(String value) {
            addCriterion("app_name >", value, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameGreaterThanOrEqualTo(String value) {
            addCriterion("app_name >=", value, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameLessThan(String value) {
            addCriterion("app_name <", value, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameLessThanOrEqualTo(String value) {
            addCriterion("app_name <=", value, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameLike(String value) {
            addCriterion("app_name like", value, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameNotLike(String value) {
            addCriterion("app_name not like", value, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameIn(List<String> values) {
            addCriterion("app_name in", values, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameNotIn(List<String> values) {
            addCriterion("app_name not in", values, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameBetween(String value1, String value2) {
            addCriterion("app_name between", value1, value2, "appName");
            return (Criteria) this;
        }

        public Criteria andAppNameNotBetween(String value1, String value2) {
            addCriterion("app_name not between", value1, value2, "appName");
            return (Criteria) this;
        }

        public Criteria andAppKeyIsNull() {
            addCriterion("app_key is null");
            return (Criteria) this;
        }

        public Criteria andAppKeyIsNotNull() {
            addCriterion("app_key is not null");
            return (Criteria) this;
        }

        public Criteria andAppKeyEqualTo(String value) {
            addCriterion("app_key =", value, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyNotEqualTo(String value) {
            addCriterion("app_key <>", value, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyGreaterThan(String value) {
            addCriterion("app_key >", value, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyGreaterThanOrEqualTo(String value) {
            addCriterion("app_key >=", value, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyLessThan(String value) {
            addCriterion("app_key <", value, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyLessThanOrEqualTo(String value) {
            addCriterion("app_key <=", value, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyLike(String value) {
            addCriterion("app_key like", value, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyNotLike(String value) {
            addCriterion("app_key not like", value, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyIn(List<String> values) {
            addCriterion("app_key in", values, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyNotIn(List<String> values) {
            addCriterion("app_key not in", values, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyBetween(String value1, String value2) {
            addCriterion("app_key between", value1, value2, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyNotBetween(String value1, String value2) {
            addCriterion("app_key not between", value1, value2, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppCreateTimeIsNull() {
            addCriterion("app_create_time is null");
            return (Criteria) this;
        }

        public Criteria andAppCreateTimeIsNotNull() {
            addCriterion("app_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andAppCreateTimeEqualTo(Date value) {
            addCriterion("app_create_time =", value, "appCreateTime");
            return (Criteria) this;
        }

        public Criteria andAppCreateTimeNotEqualTo(Date value) {
            addCriterion("app_create_time <>", value, "appCreateTime");
            return (Criteria) this;
        }

        public Criteria andAppCreateTimeGreaterThan(Date value) {
            addCriterion("app_create_time >", value, "appCreateTime");
            return (Criteria) this;
        }

        public Criteria andAppCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("app_create_time >=", value, "appCreateTime");
            return (Criteria) this;
        }

        public Criteria andAppCreateTimeLessThan(Date value) {
            addCriterion("app_create_time <", value, "appCreateTime");
            return (Criteria) this;
        }

        public Criteria andAppCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("app_create_time <=", value, "appCreateTime");
            return (Criteria) this;
        }

        public Criteria andAppCreateTimeIn(List<Date> values) {
            addCriterion("app_create_time in", values, "appCreateTime");
            return (Criteria) this;
        }

        public Criteria andAppCreateTimeNotIn(List<Date> values) {
            addCriterion("app_create_time not in", values, "appCreateTime");
            return (Criteria) this;
        }

        public Criteria andAppCreateTimeBetween(Date value1, Date value2) {
            addCriterion("app_create_time between", value1, value2, "appCreateTime");
            return (Criteria) this;
        }

        public Criteria andAppCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("app_create_time not between", value1, value2, "appCreateTime");
            return (Criteria) this;
        }

        public Criteria andAppUpdateTimeIsNull() {
            addCriterion("app_update_time is null");
            return (Criteria) this;
        }

        public Criteria andAppUpdateTimeIsNotNull() {
            addCriterion("app_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andAppUpdateTimeEqualTo(Date value) {
            addCriterion("app_update_time =", value, "appUpdateTime");
            return (Criteria) this;
        }

        public Criteria andAppUpdateTimeNotEqualTo(Date value) {
            addCriterion("app_update_time <>", value, "appUpdateTime");
            return (Criteria) this;
        }

        public Criteria andAppUpdateTimeGreaterThan(Date value) {
            addCriterion("app_update_time >", value, "appUpdateTime");
            return (Criteria) this;
        }

        public Criteria andAppUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("app_update_time >=", value, "appUpdateTime");
            return (Criteria) this;
        }

        public Criteria andAppUpdateTimeLessThan(Date value) {
            addCriterion("app_update_time <", value, "appUpdateTime");
            return (Criteria) this;
        }

        public Criteria andAppUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("app_update_time <=", value, "appUpdateTime");
            return (Criteria) this;
        }

        public Criteria andAppUpdateTimeIn(List<Date> values) {
            addCriterion("app_update_time in", values, "appUpdateTime");
            return (Criteria) this;
        }

        public Criteria andAppUpdateTimeNotIn(List<Date> values) {
            addCriterion("app_update_time not in", values, "appUpdateTime");
            return (Criteria) this;
        }

        public Criteria andAppUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("app_update_time between", value1, value2, "appUpdateTime");
            return (Criteria) this;
        }

        public Criteria andAppUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("app_update_time not between", value1, value2, "appUpdateTime");
            return (Criteria) this;
        }

        public Criteria andAppStateIsNull() {
            addCriterion("app_state is null");
            return (Criteria) this;
        }

        public Criteria andAppStateIsNotNull() {
            addCriterion("app_state is not null");
            return (Criteria) this;
        }

        public Criteria andAppStateEqualTo(Byte value) {
            addCriterion("app_state =", value, "appState");
            return (Criteria) this;
        }

        public Criteria andAppStateNotEqualTo(Byte value) {
            addCriterion("app_state <>", value, "appState");
            return (Criteria) this;
        }

        public Criteria andAppStateGreaterThan(Byte value) {
            addCriterion("app_state >", value, "appState");
            return (Criteria) this;
        }

        public Criteria andAppStateGreaterThanOrEqualTo(Byte value) {
            addCriterion("app_state >=", value, "appState");
            return (Criteria) this;
        }

        public Criteria andAppStateLessThan(Byte value) {
            addCriterion("app_state <", value, "appState");
            return (Criteria) this;
        }

        public Criteria andAppStateLessThanOrEqualTo(Byte value) {
            addCriterion("app_state <=", value, "appState");
            return (Criteria) this;
        }

        public Criteria andAppStateIn(List<Byte> values) {
            addCriterion("app_state in", values, "appState");
            return (Criteria) this;
        }

        public Criteria andAppStateNotIn(List<Byte> values) {
            addCriterion("app_state not in", values, "appState");
            return (Criteria) this;
        }

        public Criteria andAppStateBetween(Byte value1, Byte value2) {
            addCriterion("app_state between", value1, value2, "appState");
            return (Criteria) this;
        }

        public Criteria andAppStateNotBetween(Byte value1, Byte value2) {
            addCriterion("app_state not between", value1, value2, "appState");
            return (Criteria) this;
        }

        public Criteria andAppReturnUrlIsNull() {
            addCriterion("app_return_url is null");
            return (Criteria) this;
        }

        public Criteria andAppReturnUrlIsNotNull() {
            addCriterion("app_return_url is not null");
            return (Criteria) this;
        }

        public Criteria andAppReturnUrlEqualTo(String value) {
            addCriterion("app_return_url =", value, "appReturnUrl");
            return (Criteria) this;
        }

        public Criteria andAppReturnUrlNotEqualTo(String value) {
            addCriterion("app_return_url <>", value, "appReturnUrl");
            return (Criteria) this;
        }

        public Criteria andAppReturnUrlGreaterThan(String value) {
            addCriterion("app_return_url >", value, "appReturnUrl");
            return (Criteria) this;
        }

        public Criteria andAppReturnUrlGreaterThanOrEqualTo(String value) {
            addCriterion("app_return_url >=", value, "appReturnUrl");
            return (Criteria) this;
        }

        public Criteria andAppReturnUrlLessThan(String value) {
            addCriterion("app_return_url <", value, "appReturnUrl");
            return (Criteria) this;
        }

        public Criteria andAppReturnUrlLessThanOrEqualTo(String value) {
            addCriterion("app_return_url <=", value, "appReturnUrl");
            return (Criteria) this;
        }

        public Criteria andAppReturnUrlLike(String value) {
            addCriterion("app_return_url like", value, "appReturnUrl");
            return (Criteria) this;
        }

        public Criteria andAppReturnUrlNotLike(String value) {
            addCriterion("app_return_url not like", value, "appReturnUrl");
            return (Criteria) this;
        }

        public Criteria andAppReturnUrlIn(List<String> values) {
            addCriterion("app_return_url in", values, "appReturnUrl");
            return (Criteria) this;
        }

        public Criteria andAppReturnUrlNotIn(List<String> values) {
            addCriterion("app_return_url not in", values, "appReturnUrl");
            return (Criteria) this;
        }

        public Criteria andAppReturnUrlBetween(String value1, String value2) {
            addCriterion("app_return_url between", value1, value2, "appReturnUrl");
            return (Criteria) this;
        }

        public Criteria andAppReturnUrlNotBetween(String value1, String value2) {
            addCriterion("app_return_url not between", value1, value2, "appReturnUrl");
            return (Criteria) this;
        }

        public Criteria andAppNotifyUrlIsNull() {
            addCriterion("app_notify_url is null");
            return (Criteria) this;
        }

        public Criteria andAppNotifyUrlIsNotNull() {
            addCriterion("app_notify_url is not null");
            return (Criteria) this;
        }

        public Criteria andAppNotifyUrlEqualTo(String value) {
            addCriterion("app_notify_url =", value, "appNotifyUrl");
            return (Criteria) this;
        }

        public Criteria andAppNotifyUrlNotEqualTo(String value) {
            addCriterion("app_notify_url <>", value, "appNotifyUrl");
            return (Criteria) this;
        }

        public Criteria andAppNotifyUrlGreaterThan(String value) {
            addCriterion("app_notify_url >", value, "appNotifyUrl");
            return (Criteria) this;
        }

        public Criteria andAppNotifyUrlGreaterThanOrEqualTo(String value) {
            addCriterion("app_notify_url >=", value, "appNotifyUrl");
            return (Criteria) this;
        }

        public Criteria andAppNotifyUrlLessThan(String value) {
            addCriterion("app_notify_url <", value, "appNotifyUrl");
            return (Criteria) this;
        }

        public Criteria andAppNotifyUrlLessThanOrEqualTo(String value) {
            addCriterion("app_notify_url <=", value, "appNotifyUrl");
            return (Criteria) this;
        }

        public Criteria andAppNotifyUrlLike(String value) {
            addCriterion("app_notify_url like", value, "appNotifyUrl");
            return (Criteria) this;
        }

        public Criteria andAppNotifyUrlNotLike(String value) {
            addCriterion("app_notify_url not like", value, "appNotifyUrl");
            return (Criteria) this;
        }

        public Criteria andAppNotifyUrlIn(List<String> values) {
            addCriterion("app_notify_url in", values, "appNotifyUrl");
            return (Criteria) this;
        }

        public Criteria andAppNotifyUrlNotIn(List<String> values) {
            addCriterion("app_notify_url not in", values, "appNotifyUrl");
            return (Criteria) this;
        }

        public Criteria andAppNotifyUrlBetween(String value1, String value2) {
            addCriterion("app_notify_url between", value1, value2, "appNotifyUrl");
            return (Criteria) this;
        }

        public Criteria andAppNotifyUrlNotBetween(String value1, String value2) {
            addCriterion("app_notify_url not between", value1, value2, "appNotifyUrl");
            return (Criteria) this;
        }

        public Criteria andAppIdLikeInsensitive(String value) {
            addCriterion("upper(app_id) like", value.toUpperCase(), "appId");
            return (Criteria) this;
        }

        public Criteria andAppNameLikeInsensitive(String value) {
            addCriterion("upper(app_name) like", value.toUpperCase(), "appName");
            return (Criteria) this;
        }

        public Criteria andAppKeyLikeInsensitive(String value) {
            addCriterion("upper(app_key) like", value.toUpperCase(), "appKey");
            return (Criteria) this;
        }

        public Criteria andAppReturnUrlLikeInsensitive(String value) {
            addCriterion("upper(app_return_url) like", value.toUpperCase(), "appReturnUrl");
            return (Criteria) this;
        }

        public Criteria andAppNotifyUrlLikeInsensitive(String value) {
            addCriterion("upper(app_notify_url) like", value.toUpperCase(), "appNotifyUrl");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table app
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table app
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}