package org.epay.model.base;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrderRecordCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_record
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_record
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_record
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_record
     *
     * @mbg.generated
     */
    protected int limitStart = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_record
     *
     * @mbg.generated
     */
    protected int pageSize = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbg.generated
     */
    public OrderRecordCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbg.generated
     */
    public void setLimitStart(int limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbg.generated
     */
    public int getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbg.generated
     */
    public void setPageSize(int pageSize) {
        this.pageSize=pageSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbg.generated
     */
    public int getPageSize() {
        return pageSize;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_record
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOrderRecordIdIsNull() {
            addCriterion("order_record_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderRecordIdIsNotNull() {
            addCriterion("order_record_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderRecordIdEqualTo(String value) {
            addCriterion("order_record_id =", value, "orderRecordId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordIdNotEqualTo(String value) {
            addCriterion("order_record_id <>", value, "orderRecordId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordIdGreaterThan(String value) {
            addCriterion("order_record_id >", value, "orderRecordId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordIdGreaterThanOrEqualTo(String value) {
            addCriterion("order_record_id >=", value, "orderRecordId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordIdLessThan(String value) {
            addCriterion("order_record_id <", value, "orderRecordId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordIdLessThanOrEqualTo(String value) {
            addCriterion("order_record_id <=", value, "orderRecordId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordIdLike(String value) {
            addCriterion("order_record_id like", value, "orderRecordId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordIdNotLike(String value) {
            addCriterion("order_record_id not like", value, "orderRecordId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordIdIn(List<String> values) {
            addCriterion("order_record_id in", values, "orderRecordId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordIdNotIn(List<String> values) {
            addCriterion("order_record_id not in", values, "orderRecordId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordIdBetween(String value1, String value2) {
            addCriterion("order_record_id between", value1, value2, "orderRecordId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordIdNotBetween(String value1, String value2) {
            addCriterion("order_record_id not between", value1, value2, "orderRecordId");
            return (Criteria) this;
        }

        public Criteria andAppIdIsNull() {
            addCriterion("app_id is null");
            return (Criteria) this;
        }

        public Criteria andAppIdIsNotNull() {
            addCriterion("app_id is not null");
            return (Criteria) this;
        }

        public Criteria andAppIdEqualTo(String value) {
            addCriterion("app_id =", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotEqualTo(String value) {
            addCriterion("app_id <>", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdGreaterThan(String value) {
            addCriterion("app_id >", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdGreaterThanOrEqualTo(String value) {
            addCriterion("app_id >=", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLessThan(String value) {
            addCriterion("app_id <", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLessThanOrEqualTo(String value) {
            addCriterion("app_id <=", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLike(String value) {
            addCriterion("app_id like", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotLike(String value) {
            addCriterion("app_id not like", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdIn(List<String> values) {
            addCriterion("app_id in", values, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotIn(List<String> values) {
            addCriterion("app_id not in", values, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdBetween(String value1, String value2) {
            addCriterion("app_id between", value1, value2, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotBetween(String value1, String value2) {
            addCriterion("app_id not between", value1, value2, "appId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordOrderIdIsNull() {
            addCriterion("order_record_order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderRecordOrderIdIsNotNull() {
            addCriterion("order_record_order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderRecordOrderIdEqualTo(String value) {
            addCriterion("order_record_order_id =", value, "orderRecordOrderId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordOrderIdNotEqualTo(String value) {
            addCriterion("order_record_order_id <>", value, "orderRecordOrderId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordOrderIdGreaterThan(String value) {
            addCriterion("order_record_order_id >", value, "orderRecordOrderId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("order_record_order_id >=", value, "orderRecordOrderId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordOrderIdLessThan(String value) {
            addCriterion("order_record_order_id <", value, "orderRecordOrderId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordOrderIdLessThanOrEqualTo(String value) {
            addCriterion("order_record_order_id <=", value, "orderRecordOrderId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordOrderIdLike(String value) {
            addCriterion("order_record_order_id like", value, "orderRecordOrderId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordOrderIdNotLike(String value) {
            addCriterion("order_record_order_id not like", value, "orderRecordOrderId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordOrderIdIn(List<String> values) {
            addCriterion("order_record_order_id in", values, "orderRecordOrderId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordOrderIdNotIn(List<String> values) {
            addCriterion("order_record_order_id not in", values, "orderRecordOrderId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordOrderIdBetween(String value1, String value2) {
            addCriterion("order_record_order_id between", value1, value2, "orderRecordOrderId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordOrderIdNotBetween(String value1, String value2) {
            addCriterion("order_record_order_id not between", value1, value2, "orderRecordOrderId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordTotalPriceIsNull() {
            addCriterion("order_record_total_price is null");
            return (Criteria) this;
        }

        public Criteria andOrderRecordTotalPriceIsNotNull() {
            addCriterion("order_record_total_price is not null");
            return (Criteria) this;
        }

        public Criteria andOrderRecordTotalPriceEqualTo(Double value) {
            addCriterion("order_record_total_price =", value, "orderRecordTotalPrice");
            return (Criteria) this;
        }

        public Criteria andOrderRecordTotalPriceNotEqualTo(Double value) {
            addCriterion("order_record_total_price <>", value, "orderRecordTotalPrice");
            return (Criteria) this;
        }

        public Criteria andOrderRecordTotalPriceGreaterThan(Double value) {
            addCriterion("order_record_total_price >", value, "orderRecordTotalPrice");
            return (Criteria) this;
        }

        public Criteria andOrderRecordTotalPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("order_record_total_price >=", value, "orderRecordTotalPrice");
            return (Criteria) this;
        }

        public Criteria andOrderRecordTotalPriceLessThan(Double value) {
            addCriterion("order_record_total_price <", value, "orderRecordTotalPrice");
            return (Criteria) this;
        }

        public Criteria andOrderRecordTotalPriceLessThanOrEqualTo(Double value) {
            addCriterion("order_record_total_price <=", value, "orderRecordTotalPrice");
            return (Criteria) this;
        }

        public Criteria andOrderRecordTotalPriceIn(List<Double> values) {
            addCriterion("order_record_total_price in", values, "orderRecordTotalPrice");
            return (Criteria) this;
        }

        public Criteria andOrderRecordTotalPriceNotIn(List<Double> values) {
            addCriterion("order_record_total_price not in", values, "orderRecordTotalPrice");
            return (Criteria) this;
        }

        public Criteria andOrderRecordTotalPriceBetween(Double value1, Double value2) {
            addCriterion("order_record_total_price between", value1, value2, "orderRecordTotalPrice");
            return (Criteria) this;
        }

        public Criteria andOrderRecordTotalPriceNotBetween(Double value1, Double value2) {
            addCriterion("order_record_total_price not between", value1, value2, "orderRecordTotalPrice");
            return (Criteria) this;
        }

        public Criteria andOrderRecordCreateTimeIsNull() {
            addCriterion("order_record_create_time is null");
            return (Criteria) this;
        }

        public Criteria andOrderRecordCreateTimeIsNotNull() {
            addCriterion("order_record_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andOrderRecordCreateTimeEqualTo(Date value) {
            addCriterion("order_record_create_time =", value, "orderRecordCreateTime");
            return (Criteria) this;
        }

        public Criteria andOrderRecordCreateTimeNotEqualTo(Date value) {
            addCriterion("order_record_create_time <>", value, "orderRecordCreateTime");
            return (Criteria) this;
        }

        public Criteria andOrderRecordCreateTimeGreaterThan(Date value) {
            addCriterion("order_record_create_time >", value, "orderRecordCreateTime");
            return (Criteria) this;
        }

        public Criteria andOrderRecordCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("order_record_create_time >=", value, "orderRecordCreateTime");
            return (Criteria) this;
        }

        public Criteria andOrderRecordCreateTimeLessThan(Date value) {
            addCriterion("order_record_create_time <", value, "orderRecordCreateTime");
            return (Criteria) this;
        }

        public Criteria andOrderRecordCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("order_record_create_time <=", value, "orderRecordCreateTime");
            return (Criteria) this;
        }

        public Criteria andOrderRecordCreateTimeIn(List<Date> values) {
            addCriterion("order_record_create_time in", values, "orderRecordCreateTime");
            return (Criteria) this;
        }

        public Criteria andOrderRecordCreateTimeNotIn(List<Date> values) {
            addCriterion("order_record_create_time not in", values, "orderRecordCreateTime");
            return (Criteria) this;
        }

        public Criteria andOrderRecordCreateTimeBetween(Date value1, Date value2) {
            addCriterion("order_record_create_time between", value1, value2, "orderRecordCreateTime");
            return (Criteria) this;
        }

        public Criteria andOrderRecordCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("order_record_create_time not between", value1, value2, "orderRecordCreateTime");
            return (Criteria) this;
        }

        public Criteria andOrderRecordUpdateTimeIsNull() {
            addCriterion("order_record_update_time is null");
            return (Criteria) this;
        }

        public Criteria andOrderRecordUpdateTimeIsNotNull() {
            addCriterion("order_record_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andOrderRecordUpdateTimeEqualTo(Date value) {
            addCriterion("order_record_update_time =", value, "orderRecordUpdateTime");
            return (Criteria) this;
        }

        public Criteria andOrderRecordUpdateTimeNotEqualTo(Date value) {
            addCriterion("order_record_update_time <>", value, "orderRecordUpdateTime");
            return (Criteria) this;
        }

        public Criteria andOrderRecordUpdateTimeGreaterThan(Date value) {
            addCriterion("order_record_update_time >", value, "orderRecordUpdateTime");
            return (Criteria) this;
        }

        public Criteria andOrderRecordUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("order_record_update_time >=", value, "orderRecordUpdateTime");
            return (Criteria) this;
        }

        public Criteria andOrderRecordUpdateTimeLessThan(Date value) {
            addCriterion("order_record_update_time <", value, "orderRecordUpdateTime");
            return (Criteria) this;
        }

        public Criteria andOrderRecordUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("order_record_update_time <=", value, "orderRecordUpdateTime");
            return (Criteria) this;
        }

        public Criteria andOrderRecordUpdateTimeIn(List<Date> values) {
            addCriterion("order_record_update_time in", values, "orderRecordUpdateTime");
            return (Criteria) this;
        }

        public Criteria andOrderRecordUpdateTimeNotIn(List<Date> values) {
            addCriterion("order_record_update_time not in", values, "orderRecordUpdateTime");
            return (Criteria) this;
        }

        public Criteria andOrderRecordUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("order_record_update_time between", value1, value2, "orderRecordUpdateTime");
            return (Criteria) this;
        }

        public Criteria andOrderRecordUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("order_record_update_time not between", value1, value2, "orderRecordUpdateTime");
            return (Criteria) this;
        }

        public Criteria andOrderRecordPayStatusIsNull() {
            addCriterion("order_record_pay_status is null");
            return (Criteria) this;
        }

        public Criteria andOrderRecordPayStatusIsNotNull() {
            addCriterion("order_record_pay_status is not null");
            return (Criteria) this;
        }

        public Criteria andOrderRecordPayStatusEqualTo(Byte value) {
            addCriterion("order_record_pay_status =", value, "orderRecordPayStatus");
            return (Criteria) this;
        }

        public Criteria andOrderRecordPayStatusNotEqualTo(Byte value) {
            addCriterion("order_record_pay_status <>", value, "orderRecordPayStatus");
            return (Criteria) this;
        }

        public Criteria andOrderRecordPayStatusGreaterThan(Byte value) {
            addCriterion("order_record_pay_status >", value, "orderRecordPayStatus");
            return (Criteria) this;
        }

        public Criteria andOrderRecordPayStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("order_record_pay_status >=", value, "orderRecordPayStatus");
            return (Criteria) this;
        }

        public Criteria andOrderRecordPayStatusLessThan(Byte value) {
            addCriterion("order_record_pay_status <", value, "orderRecordPayStatus");
            return (Criteria) this;
        }

        public Criteria andOrderRecordPayStatusLessThanOrEqualTo(Byte value) {
            addCriterion("order_record_pay_status <=", value, "orderRecordPayStatus");
            return (Criteria) this;
        }

        public Criteria andOrderRecordPayStatusIn(List<Byte> values) {
            addCriterion("order_record_pay_status in", values, "orderRecordPayStatus");
            return (Criteria) this;
        }

        public Criteria andOrderRecordPayStatusNotIn(List<Byte> values) {
            addCriterion("order_record_pay_status not in", values, "orderRecordPayStatus");
            return (Criteria) this;
        }

        public Criteria andOrderRecordPayStatusBetween(Byte value1, Byte value2) {
            addCriterion("order_record_pay_status between", value1, value2, "orderRecordPayStatus");
            return (Criteria) this;
        }

        public Criteria andOrderRecordPayStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("order_record_pay_status not between", value1, value2, "orderRecordPayStatus");
            return (Criteria) this;
        }

        public Criteria andOrderRecordStatusIsNull() {
            addCriterion("order_record_status is null");
            return (Criteria) this;
        }

        public Criteria andOrderRecordStatusIsNotNull() {
            addCriterion("order_record_status is not null");
            return (Criteria) this;
        }

        public Criteria andOrderRecordStatusEqualTo(Byte value) {
            addCriterion("order_record_status =", value, "orderRecordStatus");
            return (Criteria) this;
        }

        public Criteria andOrderRecordStatusNotEqualTo(Byte value) {
            addCriterion("order_record_status <>", value, "orderRecordStatus");
            return (Criteria) this;
        }

        public Criteria andOrderRecordStatusGreaterThan(Byte value) {
            addCriterion("order_record_status >", value, "orderRecordStatus");
            return (Criteria) this;
        }

        public Criteria andOrderRecordStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("order_record_status >=", value, "orderRecordStatus");
            return (Criteria) this;
        }

        public Criteria andOrderRecordStatusLessThan(Byte value) {
            addCriterion("order_record_status <", value, "orderRecordStatus");
            return (Criteria) this;
        }

        public Criteria andOrderRecordStatusLessThanOrEqualTo(Byte value) {
            addCriterion("order_record_status <=", value, "orderRecordStatus");
            return (Criteria) this;
        }

        public Criteria andOrderRecordStatusIn(List<Byte> values) {
            addCriterion("order_record_status in", values, "orderRecordStatus");
            return (Criteria) this;
        }

        public Criteria andOrderRecordStatusNotIn(List<Byte> values) {
            addCriterion("order_record_status not in", values, "orderRecordStatus");
            return (Criteria) this;
        }

        public Criteria andOrderRecordStatusBetween(Byte value1, Byte value2) {
            addCriterion("order_record_status between", value1, value2, "orderRecordStatus");
            return (Criteria) this;
        }

        public Criteria andOrderRecordStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("order_record_status not between", value1, value2, "orderRecordStatus");
            return (Criteria) this;
        }

        public Criteria andOrderRecordUserIdIsNull() {
            addCriterion("order_record_user_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderRecordUserIdIsNotNull() {
            addCriterion("order_record_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderRecordUserIdEqualTo(String value) {
            addCriterion("order_record_user_id =", value, "orderRecordUserId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordUserIdNotEqualTo(String value) {
            addCriterion("order_record_user_id <>", value, "orderRecordUserId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordUserIdGreaterThan(String value) {
            addCriterion("order_record_user_id >", value, "orderRecordUserId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("order_record_user_id >=", value, "orderRecordUserId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordUserIdLessThan(String value) {
            addCriterion("order_record_user_id <", value, "orderRecordUserId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordUserIdLessThanOrEqualTo(String value) {
            addCriterion("order_record_user_id <=", value, "orderRecordUserId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordUserIdLike(String value) {
            addCriterion("order_record_user_id like", value, "orderRecordUserId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordUserIdNotLike(String value) {
            addCriterion("order_record_user_id not like", value, "orderRecordUserId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordUserIdIn(List<String> values) {
            addCriterion("order_record_user_id in", values, "orderRecordUserId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordUserIdNotIn(List<String> values) {
            addCriterion("order_record_user_id not in", values, "orderRecordUserId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordUserIdBetween(String value1, String value2) {
            addCriterion("order_record_user_id between", value1, value2, "orderRecordUserId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordUserIdNotBetween(String value1, String value2) {
            addCriterion("order_record_user_id not between", value1, value2, "orderRecordUserId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordPayChannelIsNull() {
            addCriterion("order_record_pay_channel is null");
            return (Criteria) this;
        }

        public Criteria andOrderRecordPayChannelIsNotNull() {
            addCriterion("order_record_pay_channel is not null");
            return (Criteria) this;
        }

        public Criteria andOrderRecordPayChannelEqualTo(Byte value) {
            addCriterion("order_record_pay_channel =", value, "orderRecordPayChannel");
            return (Criteria) this;
        }

        public Criteria andOrderRecordPayChannelNotEqualTo(Byte value) {
            addCriterion("order_record_pay_channel <>", value, "orderRecordPayChannel");
            return (Criteria) this;
        }

        public Criteria andOrderRecordPayChannelGreaterThan(Byte value) {
            addCriterion("order_record_pay_channel >", value, "orderRecordPayChannel");
            return (Criteria) this;
        }

        public Criteria andOrderRecordPayChannelGreaterThanOrEqualTo(Byte value) {
            addCriterion("order_record_pay_channel >=", value, "orderRecordPayChannel");
            return (Criteria) this;
        }

        public Criteria andOrderRecordPayChannelLessThan(Byte value) {
            addCriterion("order_record_pay_channel <", value, "orderRecordPayChannel");
            return (Criteria) this;
        }

        public Criteria andOrderRecordPayChannelLessThanOrEqualTo(Byte value) {
            addCriterion("order_record_pay_channel <=", value, "orderRecordPayChannel");
            return (Criteria) this;
        }

        public Criteria andOrderRecordPayChannelIn(List<Byte> values) {
            addCriterion("order_record_pay_channel in", values, "orderRecordPayChannel");
            return (Criteria) this;
        }

        public Criteria andOrderRecordPayChannelNotIn(List<Byte> values) {
            addCriterion("order_record_pay_channel not in", values, "orderRecordPayChannel");
            return (Criteria) this;
        }

        public Criteria andOrderRecordPayChannelBetween(Byte value1, Byte value2) {
            addCriterion("order_record_pay_channel between", value1, value2, "orderRecordPayChannel");
            return (Criteria) this;
        }

        public Criteria andOrderRecordPayChannelNotBetween(Byte value1, Byte value2) {
            addCriterion("order_record_pay_channel not between", value1, value2, "orderRecordPayChannel");
            return (Criteria) this;
        }

        public Criteria andOrderRecordUserNameIsNull() {
            addCriterion("order_record_user_name is null");
            return (Criteria) this;
        }

        public Criteria andOrderRecordUserNameIsNotNull() {
            addCriterion("order_record_user_name is not null");
            return (Criteria) this;
        }

        public Criteria andOrderRecordUserNameEqualTo(String value) {
            addCriterion("order_record_user_name =", value, "orderRecordUserName");
            return (Criteria) this;
        }

        public Criteria andOrderRecordUserNameNotEqualTo(String value) {
            addCriterion("order_record_user_name <>", value, "orderRecordUserName");
            return (Criteria) this;
        }

        public Criteria andOrderRecordUserNameGreaterThan(String value) {
            addCriterion("order_record_user_name >", value, "orderRecordUserName");
            return (Criteria) this;
        }

        public Criteria andOrderRecordUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("order_record_user_name >=", value, "orderRecordUserName");
            return (Criteria) this;
        }

        public Criteria andOrderRecordUserNameLessThan(String value) {
            addCriterion("order_record_user_name <", value, "orderRecordUserName");
            return (Criteria) this;
        }

        public Criteria andOrderRecordUserNameLessThanOrEqualTo(String value) {
            addCriterion("order_record_user_name <=", value, "orderRecordUserName");
            return (Criteria) this;
        }

        public Criteria andOrderRecordUserNameLike(String value) {
            addCriterion("order_record_user_name like", value, "orderRecordUserName");
            return (Criteria) this;
        }

        public Criteria andOrderRecordUserNameNotLike(String value) {
            addCriterion("order_record_user_name not like", value, "orderRecordUserName");
            return (Criteria) this;
        }

        public Criteria andOrderRecordUserNameIn(List<String> values) {
            addCriterion("order_record_user_name in", values, "orderRecordUserName");
            return (Criteria) this;
        }

        public Criteria andOrderRecordUserNameNotIn(List<String> values) {
            addCriterion("order_record_user_name not in", values, "orderRecordUserName");
            return (Criteria) this;
        }

        public Criteria andOrderRecordUserNameBetween(String value1, String value2) {
            addCriterion("order_record_user_name between", value1, value2, "orderRecordUserName");
            return (Criteria) this;
        }

        public Criteria andOrderRecordUserNameNotBetween(String value1, String value2) {
            addCriterion("order_record_user_name not between", value1, value2, "orderRecordUserName");
            return (Criteria) this;
        }

        public Criteria andOrderRecordReturnUrlIsNull() {
            addCriterion("order_record_return_url is null");
            return (Criteria) this;
        }

        public Criteria andOrderRecordReturnUrlIsNotNull() {
            addCriterion("order_record_return_url is not null");
            return (Criteria) this;
        }

        public Criteria andOrderRecordReturnUrlEqualTo(String value) {
            addCriterion("order_record_return_url =", value, "orderRecordReturnUrl");
            return (Criteria) this;
        }

        public Criteria andOrderRecordReturnUrlNotEqualTo(String value) {
            addCriterion("order_record_return_url <>", value, "orderRecordReturnUrl");
            return (Criteria) this;
        }

        public Criteria andOrderRecordReturnUrlGreaterThan(String value) {
            addCriterion("order_record_return_url >", value, "orderRecordReturnUrl");
            return (Criteria) this;
        }

        public Criteria andOrderRecordReturnUrlGreaterThanOrEqualTo(String value) {
            addCriterion("order_record_return_url >=", value, "orderRecordReturnUrl");
            return (Criteria) this;
        }

        public Criteria andOrderRecordReturnUrlLessThan(String value) {
            addCriterion("order_record_return_url <", value, "orderRecordReturnUrl");
            return (Criteria) this;
        }

        public Criteria andOrderRecordReturnUrlLessThanOrEqualTo(String value) {
            addCriterion("order_record_return_url <=", value, "orderRecordReturnUrl");
            return (Criteria) this;
        }

        public Criteria andOrderRecordReturnUrlLike(String value) {
            addCriterion("order_record_return_url like", value, "orderRecordReturnUrl");
            return (Criteria) this;
        }

        public Criteria andOrderRecordReturnUrlNotLike(String value) {
            addCriterion("order_record_return_url not like", value, "orderRecordReturnUrl");
            return (Criteria) this;
        }

        public Criteria andOrderRecordReturnUrlIn(List<String> values) {
            addCriterion("order_record_return_url in", values, "orderRecordReturnUrl");
            return (Criteria) this;
        }

        public Criteria andOrderRecordReturnUrlNotIn(List<String> values) {
            addCriterion("order_record_return_url not in", values, "orderRecordReturnUrl");
            return (Criteria) this;
        }

        public Criteria andOrderRecordReturnUrlBetween(String value1, String value2) {
            addCriterion("order_record_return_url between", value1, value2, "orderRecordReturnUrl");
            return (Criteria) this;
        }

        public Criteria andOrderRecordReturnUrlNotBetween(String value1, String value2) {
            addCriterion("order_record_return_url not between", value1, value2, "orderRecordReturnUrl");
            return (Criteria) this;
        }

        public Criteria andOrderRecordNotifyUrlIsNull() {
            addCriterion("order_record_notify_url is null");
            return (Criteria) this;
        }

        public Criteria andOrderRecordNotifyUrlIsNotNull() {
            addCriterion("order_record_notify_url is not null");
            return (Criteria) this;
        }

        public Criteria andOrderRecordNotifyUrlEqualTo(String value) {
            addCriterion("order_record_notify_url =", value, "orderRecordNotifyUrl");
            return (Criteria) this;
        }

        public Criteria andOrderRecordNotifyUrlNotEqualTo(String value) {
            addCriterion("order_record_notify_url <>", value, "orderRecordNotifyUrl");
            return (Criteria) this;
        }

        public Criteria andOrderRecordNotifyUrlGreaterThan(String value) {
            addCriterion("order_record_notify_url >", value, "orderRecordNotifyUrl");
            return (Criteria) this;
        }

        public Criteria andOrderRecordNotifyUrlGreaterThanOrEqualTo(String value) {
            addCriterion("order_record_notify_url >=", value, "orderRecordNotifyUrl");
            return (Criteria) this;
        }

        public Criteria andOrderRecordNotifyUrlLessThan(String value) {
            addCriterion("order_record_notify_url <", value, "orderRecordNotifyUrl");
            return (Criteria) this;
        }

        public Criteria andOrderRecordNotifyUrlLessThanOrEqualTo(String value) {
            addCriterion("order_record_notify_url <=", value, "orderRecordNotifyUrl");
            return (Criteria) this;
        }

        public Criteria andOrderRecordNotifyUrlLike(String value) {
            addCriterion("order_record_notify_url like", value, "orderRecordNotifyUrl");
            return (Criteria) this;
        }

        public Criteria andOrderRecordNotifyUrlNotLike(String value) {
            addCriterion("order_record_notify_url not like", value, "orderRecordNotifyUrl");
            return (Criteria) this;
        }

        public Criteria andOrderRecordNotifyUrlIn(List<String> values) {
            addCriterion("order_record_notify_url in", values, "orderRecordNotifyUrl");
            return (Criteria) this;
        }

        public Criteria andOrderRecordNotifyUrlNotIn(List<String> values) {
            addCriterion("order_record_notify_url not in", values, "orderRecordNotifyUrl");
            return (Criteria) this;
        }

        public Criteria andOrderRecordNotifyUrlBetween(String value1, String value2) {
            addCriterion("order_record_notify_url between", value1, value2, "orderRecordNotifyUrl");
            return (Criteria) this;
        }

        public Criteria andOrderRecordNotifyUrlNotBetween(String value1, String value2) {
            addCriterion("order_record_notify_url not between", value1, value2, "orderRecordNotifyUrl");
            return (Criteria) this;
        }

        public Criteria andOrderRecordNotifyResultIsNull() {
            addCriterion("order_record_notify_result is null");
            return (Criteria) this;
        }

        public Criteria andOrderRecordNotifyResultIsNotNull() {
            addCriterion("order_record_notify_result is not null");
            return (Criteria) this;
        }

        public Criteria andOrderRecordNotifyResultEqualTo(Byte value) {
            addCriterion("order_record_notify_result =", value, "orderRecordNotifyResult");
            return (Criteria) this;
        }

        public Criteria andOrderRecordNotifyResultNotEqualTo(Byte value) {
            addCriterion("order_record_notify_result <>", value, "orderRecordNotifyResult");
            return (Criteria) this;
        }

        public Criteria andOrderRecordNotifyResultGreaterThan(Byte value) {
            addCriterion("order_record_notify_result >", value, "orderRecordNotifyResult");
            return (Criteria) this;
        }

        public Criteria andOrderRecordNotifyResultGreaterThanOrEqualTo(Byte value) {
            addCriterion("order_record_notify_result >=", value, "orderRecordNotifyResult");
            return (Criteria) this;
        }

        public Criteria andOrderRecordNotifyResultLessThan(Byte value) {
            addCriterion("order_record_notify_result <", value, "orderRecordNotifyResult");
            return (Criteria) this;
        }

        public Criteria andOrderRecordNotifyResultLessThanOrEqualTo(Byte value) {
            addCriterion("order_record_notify_result <=", value, "orderRecordNotifyResult");
            return (Criteria) this;
        }

        public Criteria andOrderRecordNotifyResultIn(List<Byte> values) {
            addCriterion("order_record_notify_result in", values, "orderRecordNotifyResult");
            return (Criteria) this;
        }

        public Criteria andOrderRecordNotifyResultNotIn(List<Byte> values) {
            addCriterion("order_record_notify_result not in", values, "orderRecordNotifyResult");
            return (Criteria) this;
        }

        public Criteria andOrderRecordNotifyResultBetween(Byte value1, Byte value2) {
            addCriterion("order_record_notify_result between", value1, value2, "orderRecordNotifyResult");
            return (Criteria) this;
        }

        public Criteria andOrderRecordNotifyResultNotBetween(Byte value1, Byte value2) {
            addCriterion("order_record_notify_result not between", value1, value2, "orderRecordNotifyResult");
            return (Criteria) this;
        }

        public Criteria andOrderRecordNotifyTimeIsNull() {
            addCriterion("order_record_notify_time is null");
            return (Criteria) this;
        }

        public Criteria andOrderRecordNotifyTimeIsNotNull() {
            addCriterion("order_record_notify_time is not null");
            return (Criteria) this;
        }

        public Criteria andOrderRecordNotifyTimeEqualTo(Byte value) {
            addCriterion("order_record_notify_time =", value, "orderRecordNotifyTime");
            return (Criteria) this;
        }

        public Criteria andOrderRecordNotifyTimeNotEqualTo(Byte value) {
            addCriterion("order_record_notify_time <>", value, "orderRecordNotifyTime");
            return (Criteria) this;
        }

        public Criteria andOrderRecordNotifyTimeGreaterThan(Byte value) {
            addCriterion("order_record_notify_time >", value, "orderRecordNotifyTime");
            return (Criteria) this;
        }

        public Criteria andOrderRecordNotifyTimeGreaterThanOrEqualTo(Byte value) {
            addCriterion("order_record_notify_time >=", value, "orderRecordNotifyTime");
            return (Criteria) this;
        }

        public Criteria andOrderRecordNotifyTimeLessThan(Byte value) {
            addCriterion("order_record_notify_time <", value, "orderRecordNotifyTime");
            return (Criteria) this;
        }

        public Criteria andOrderRecordNotifyTimeLessThanOrEqualTo(Byte value) {
            addCriterion("order_record_notify_time <=", value, "orderRecordNotifyTime");
            return (Criteria) this;
        }

        public Criteria andOrderRecordNotifyTimeIn(List<Byte> values) {
            addCriterion("order_record_notify_time in", values, "orderRecordNotifyTime");
            return (Criteria) this;
        }

        public Criteria andOrderRecordNotifyTimeNotIn(List<Byte> values) {
            addCriterion("order_record_notify_time not in", values, "orderRecordNotifyTime");
            return (Criteria) this;
        }

        public Criteria andOrderRecordNotifyTimeBetween(Byte value1, Byte value2) {
            addCriterion("order_record_notify_time between", value1, value2, "orderRecordNotifyTime");
            return (Criteria) this;
        }

        public Criteria andOrderRecordNotifyTimeNotBetween(Byte value1, Byte value2) {
            addCriterion("order_record_notify_time not between", value1, value2, "orderRecordNotifyTime");
            return (Criteria) this;
        }

        public Criteria andTradeNoIsNull() {
            addCriterion("trade_no is null");
            return (Criteria) this;
        }

        public Criteria andTradeNoIsNotNull() {
            addCriterion("trade_no is not null");
            return (Criteria) this;
        }

        public Criteria andTradeNoEqualTo(String value) {
            addCriterion("trade_no =", value, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoNotEqualTo(String value) {
            addCriterion("trade_no <>", value, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoGreaterThan(String value) {
            addCriterion("trade_no >", value, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoGreaterThanOrEqualTo(String value) {
            addCriterion("trade_no >=", value, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoLessThan(String value) {
            addCriterion("trade_no <", value, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoLessThanOrEqualTo(String value) {
            addCriterion("trade_no <=", value, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoLike(String value) {
            addCriterion("trade_no like", value, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoNotLike(String value) {
            addCriterion("trade_no not like", value, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoIn(List<String> values) {
            addCriterion("trade_no in", values, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoNotIn(List<String> values) {
            addCriterion("trade_no not in", values, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoBetween(String value1, String value2) {
            addCriterion("trade_no between", value1, value2, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andTradeNoNotBetween(String value1, String value2) {
            addCriterion("trade_no not between", value1, value2, "tradeNo");
            return (Criteria) this;
        }

        public Criteria andBuyerEmailIsNull() {
            addCriterion("buyer_email is null");
            return (Criteria) this;
        }

        public Criteria andBuyerEmailIsNotNull() {
            addCriterion("buyer_email is not null");
            return (Criteria) this;
        }

        public Criteria andBuyerEmailEqualTo(String value) {
            addCriterion("buyer_email =", value, "buyerEmail");
            return (Criteria) this;
        }

        public Criteria andBuyerEmailNotEqualTo(String value) {
            addCriterion("buyer_email <>", value, "buyerEmail");
            return (Criteria) this;
        }

        public Criteria andBuyerEmailGreaterThan(String value) {
            addCriterion("buyer_email >", value, "buyerEmail");
            return (Criteria) this;
        }

        public Criteria andBuyerEmailGreaterThanOrEqualTo(String value) {
            addCriterion("buyer_email >=", value, "buyerEmail");
            return (Criteria) this;
        }

        public Criteria andBuyerEmailLessThan(String value) {
            addCriterion("buyer_email <", value, "buyerEmail");
            return (Criteria) this;
        }

        public Criteria andBuyerEmailLessThanOrEqualTo(String value) {
            addCriterion("buyer_email <=", value, "buyerEmail");
            return (Criteria) this;
        }

        public Criteria andBuyerEmailLike(String value) {
            addCriterion("buyer_email like", value, "buyerEmail");
            return (Criteria) this;
        }

        public Criteria andBuyerEmailNotLike(String value) {
            addCriterion("buyer_email not like", value, "buyerEmail");
            return (Criteria) this;
        }

        public Criteria andBuyerEmailIn(List<String> values) {
            addCriterion("buyer_email in", values, "buyerEmail");
            return (Criteria) this;
        }

        public Criteria andBuyerEmailNotIn(List<String> values) {
            addCriterion("buyer_email not in", values, "buyerEmail");
            return (Criteria) this;
        }

        public Criteria andBuyerEmailBetween(String value1, String value2) {
            addCriterion("buyer_email between", value1, value2, "buyerEmail");
            return (Criteria) this;
        }

        public Criteria andBuyerEmailNotBetween(String value1, String value2) {
            addCriterion("buyer_email not between", value1, value2, "buyerEmail");
            return (Criteria) this;
        }

        public Criteria andNotifyTimeIsNull() {
            addCriterion("notify_time is null");
            return (Criteria) this;
        }

        public Criteria andNotifyTimeIsNotNull() {
            addCriterion("notify_time is not null");
            return (Criteria) this;
        }

        public Criteria andNotifyTimeEqualTo(Date value) {
            addCriterion("notify_time =", value, "notifyTime");
            return (Criteria) this;
        }

        public Criteria andNotifyTimeNotEqualTo(Date value) {
            addCriterion("notify_time <>", value, "notifyTime");
            return (Criteria) this;
        }

        public Criteria andNotifyTimeGreaterThan(Date value) {
            addCriterion("notify_time >", value, "notifyTime");
            return (Criteria) this;
        }

        public Criteria andNotifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("notify_time >=", value, "notifyTime");
            return (Criteria) this;
        }

        public Criteria andNotifyTimeLessThan(Date value) {
            addCriterion("notify_time <", value, "notifyTime");
            return (Criteria) this;
        }

        public Criteria andNotifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("notify_time <=", value, "notifyTime");
            return (Criteria) this;
        }

        public Criteria andNotifyTimeIn(List<Date> values) {
            addCriterion("notify_time in", values, "notifyTime");
            return (Criteria) this;
        }

        public Criteria andNotifyTimeNotIn(List<Date> values) {
            addCriterion("notify_time not in", values, "notifyTime");
            return (Criteria) this;
        }

        public Criteria andNotifyTimeBetween(Date value1, Date value2) {
            addCriterion("notify_time between", value1, value2, "notifyTime");
            return (Criteria) this;
        }

        public Criteria andNotifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("notify_time not between", value1, value2, "notifyTime");
            return (Criteria) this;
        }

        public Criteria andBuyerIdIsNull() {
            addCriterion("buyer_id is null");
            return (Criteria) this;
        }

        public Criteria andBuyerIdIsNotNull() {
            addCriterion("buyer_id is not null");
            return (Criteria) this;
        }

        public Criteria andBuyerIdEqualTo(String value) {
            addCriterion("buyer_id =", value, "buyerId");
            return (Criteria) this;
        }

        public Criteria andBuyerIdNotEqualTo(String value) {
            addCriterion("buyer_id <>", value, "buyerId");
            return (Criteria) this;
        }

        public Criteria andBuyerIdGreaterThan(String value) {
            addCriterion("buyer_id >", value, "buyerId");
            return (Criteria) this;
        }

        public Criteria andBuyerIdGreaterThanOrEqualTo(String value) {
            addCriterion("buyer_id >=", value, "buyerId");
            return (Criteria) this;
        }

        public Criteria andBuyerIdLessThan(String value) {
            addCriterion("buyer_id <", value, "buyerId");
            return (Criteria) this;
        }

        public Criteria andBuyerIdLessThanOrEqualTo(String value) {
            addCriterion("buyer_id <=", value, "buyerId");
            return (Criteria) this;
        }

        public Criteria andBuyerIdLike(String value) {
            addCriterion("buyer_id like", value, "buyerId");
            return (Criteria) this;
        }

        public Criteria andBuyerIdNotLike(String value) {
            addCriterion("buyer_id not like", value, "buyerId");
            return (Criteria) this;
        }

        public Criteria andBuyerIdIn(List<String> values) {
            addCriterion("buyer_id in", values, "buyerId");
            return (Criteria) this;
        }

        public Criteria andBuyerIdNotIn(List<String> values) {
            addCriterion("buyer_id not in", values, "buyerId");
            return (Criteria) this;
        }

        public Criteria andBuyerIdBetween(String value1, String value2) {
            addCriterion("buyer_id between", value1, value2, "buyerId");
            return (Criteria) this;
        }

        public Criteria andBuyerIdNotBetween(String value1, String value2) {
            addCriterion("buyer_id not between", value1, value2, "buyerId");
            return (Criteria) this;
        }

        public Criteria andTotalFeeIsNull() {
            addCriterion("total_fee is null");
            return (Criteria) this;
        }

        public Criteria andTotalFeeIsNotNull() {
            addCriterion("total_fee is not null");
            return (Criteria) this;
        }

        public Criteria andTotalFeeEqualTo(Double value) {
            addCriterion("total_fee =", value, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeNotEqualTo(Double value) {
            addCriterion("total_fee <>", value, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeGreaterThan(Double value) {
            addCriterion("total_fee >", value, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeGreaterThanOrEqualTo(Double value) {
            addCriterion("total_fee >=", value, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeLessThan(Double value) {
            addCriterion("total_fee <", value, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeLessThanOrEqualTo(Double value) {
            addCriterion("total_fee <=", value, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeIn(List<Double> values) {
            addCriterion("total_fee in", values, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeNotIn(List<Double> values) {
            addCriterion("total_fee not in", values, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeBetween(Double value1, Double value2) {
            addCriterion("total_fee between", value1, value2, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeNotBetween(Double value1, Double value2) {
            addCriterion("total_fee not between", value1, value2, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTradeStatusIsNull() {
            addCriterion("trade_status is null");
            return (Criteria) this;
        }

        public Criteria andTradeStatusIsNotNull() {
            addCriterion("trade_status is not null");
            return (Criteria) this;
        }

        public Criteria andTradeStatusEqualTo(String value) {
            addCriterion("trade_status =", value, "tradeStatus");
            return (Criteria) this;
        }

        public Criteria andTradeStatusNotEqualTo(String value) {
            addCriterion("trade_status <>", value, "tradeStatus");
            return (Criteria) this;
        }

        public Criteria andTradeStatusGreaterThan(String value) {
            addCriterion("trade_status >", value, "tradeStatus");
            return (Criteria) this;
        }

        public Criteria andTradeStatusGreaterThanOrEqualTo(String value) {
            addCriterion("trade_status >=", value, "tradeStatus");
            return (Criteria) this;
        }

        public Criteria andTradeStatusLessThan(String value) {
            addCriterion("trade_status <", value, "tradeStatus");
            return (Criteria) this;
        }

        public Criteria andTradeStatusLessThanOrEqualTo(String value) {
            addCriterion("trade_status <=", value, "tradeStatus");
            return (Criteria) this;
        }

        public Criteria andTradeStatusLike(String value) {
            addCriterion("trade_status like", value, "tradeStatus");
            return (Criteria) this;
        }

        public Criteria andTradeStatusNotLike(String value) {
            addCriterion("trade_status not like", value, "tradeStatus");
            return (Criteria) this;
        }

        public Criteria andTradeStatusIn(List<String> values) {
            addCriterion("trade_status in", values, "tradeStatus");
            return (Criteria) this;
        }

        public Criteria andTradeStatusNotIn(List<String> values) {
            addCriterion("trade_status not in", values, "tradeStatus");
            return (Criteria) this;
        }

        public Criteria andTradeStatusBetween(String value1, String value2) {
            addCriterion("trade_status between", value1, value2, "tradeStatus");
            return (Criteria) this;
        }

        public Criteria andTradeStatusNotBetween(String value1, String value2) {
            addCriterion("trade_status not between", value1, value2, "tradeStatus");
            return (Criteria) this;
        }

        public Criteria andOrderRecordIdLikeInsensitive(String value) {
            addCriterion("upper(order_record_id) like", value.toUpperCase(), "orderRecordId");
            return (Criteria) this;
        }

        public Criteria andAppIdLikeInsensitive(String value) {
            addCriterion("upper(app_id) like", value.toUpperCase(), "appId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordOrderIdLikeInsensitive(String value) {
            addCriterion("upper(order_record_order_id) like", value.toUpperCase(), "orderRecordOrderId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordUserIdLikeInsensitive(String value) {
            addCriterion("upper(order_record_user_id) like", value.toUpperCase(), "orderRecordUserId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordUserNameLikeInsensitive(String value) {
            addCriterion("upper(order_record_user_name) like", value.toUpperCase(), "orderRecordUserName");
            return (Criteria) this;
        }

        public Criteria andOrderRecordReturnUrlLikeInsensitive(String value) {
            addCriterion("upper(order_record_return_url) like", value.toUpperCase(), "orderRecordReturnUrl");
            return (Criteria) this;
        }

        public Criteria andOrderRecordNotifyUrlLikeInsensitive(String value) {
            addCriterion("upper(order_record_notify_url) like", value.toUpperCase(), "orderRecordNotifyUrl");
            return (Criteria) this;
        }

        public Criteria andTradeNoLikeInsensitive(String value) {
            addCriterion("upper(trade_no) like", value.toUpperCase(), "tradeNo");
            return (Criteria) this;
        }

        public Criteria andBuyerEmailLikeInsensitive(String value) {
            addCriterion("upper(buyer_email) like", value.toUpperCase(), "buyerEmail");
            return (Criteria) this;
        }

        public Criteria andBuyerIdLikeInsensitive(String value) {
            addCriterion("upper(buyer_id) like", value.toUpperCase(), "buyerId");
            return (Criteria) this;
        }

        public Criteria andTradeStatusLikeInsensitive(String value) {
            addCriterion("upper(trade_status) like", value.toUpperCase(), "tradeStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_record
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_record
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}