package org.epay.model.base;

import java.io.Serializable;
import java.util.Date;

public class OrderRecord implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_record.order_record_id
     *
     * @mbg.generated
     */
    private String orderRecordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_record.app_id
     *
     * @mbg.generated
     */
    private String appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_record.order_record_order_id
     *
     * @mbg.generated
     */
    private String orderRecordOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_record.order_record_total_price
     *
     * @mbg.generated
     */
    private Double orderRecordTotalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_record.order_record_create_time
     *
     * @mbg.generated
     */
    private Date orderRecordCreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_record.order_record_update_time
     *
     * @mbg.generated
     */
    private Date orderRecordUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_record.order_record_pay_status
     *
     * @mbg.generated
     */
    private Byte orderRecordPayStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_record.order_record_status
     *
     * @mbg.generated
     */
    private Byte orderRecordStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_record.order_record_user_id
     *
     * @mbg.generated
     */
    private String orderRecordUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_record.order_record_pay_channel
     *
     * @mbg.generated
     */
    private Byte orderRecordPayChannel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_record.order_record_user_name
     *
     * @mbg.generated
     */
    private String orderRecordUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_record.order_record_return_url
     *
     * @mbg.generated
     */
    private String orderRecordReturnUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_record.order_record_notify_url
     *
     * @mbg.generated
     */
    private String orderRecordNotifyUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_record.order_record_notify_result
     *
     * @mbg.generated
     */
    private Byte orderRecordNotifyResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_record.order_record_notify_time
     *
     * @mbg.generated
     */
    private Byte orderRecordNotifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_record.trade_no
     *
     * @mbg.generated
     */
    private String tradeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_record.buyer_email
     *
     * @mbg.generated
     */
    private String buyerEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_record.notify_time
     *
     * @mbg.generated
     */
    private Date notifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_record.buyer_id
     *
     * @mbg.generated
     */
    private String buyerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_record.total_fee
     *
     * @mbg.generated
     */
    private Double totalFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_record.trade_status
     *
     * @mbg.generated
     */
    private String tradeStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_record.order_record_order_detail
     *
     * @mbg.generated
     */
    private String orderRecordOrderDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_record
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_record.order_record_id
     *
     * @return the value of order_record.order_record_id
     *
     * @mbg.generated
     */
    public String getOrderRecordId() {
        return orderRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_record.order_record_id
     *
     * @param orderRecordId the value for order_record.order_record_id
     *
     * @mbg.generated
     */
    public void setOrderRecordId(String orderRecordId) {
        this.orderRecordId = orderRecordId == null ? null : orderRecordId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_record.app_id
     *
     * @return the value of order_record.app_id
     *
     * @mbg.generated
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_record.app_id
     *
     * @param appId the value for order_record.app_id
     *
     * @mbg.generated
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_record.order_record_order_id
     *
     * @return the value of order_record.order_record_order_id
     *
     * @mbg.generated
     */
    public String getOrderRecordOrderId() {
        return orderRecordOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_record.order_record_order_id
     *
     * @param orderRecordOrderId the value for order_record.order_record_order_id
     *
     * @mbg.generated
     */
    public void setOrderRecordOrderId(String orderRecordOrderId) {
        this.orderRecordOrderId = orderRecordOrderId == null ? null : orderRecordOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_record.order_record_total_price
     *
     * @return the value of order_record.order_record_total_price
     *
     * @mbg.generated
     */
    public Double getOrderRecordTotalPrice() {
        return orderRecordTotalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_record.order_record_total_price
     *
     * @param orderRecordTotalPrice the value for order_record.order_record_total_price
     *
     * @mbg.generated
     */
    public void setOrderRecordTotalPrice(Double orderRecordTotalPrice) {
        this.orderRecordTotalPrice = orderRecordTotalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_record.order_record_create_time
     *
     * @return the value of order_record.order_record_create_time
     *
     * @mbg.generated
     */
    public Date getOrderRecordCreateTime() {
        return orderRecordCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_record.order_record_create_time
     *
     * @param orderRecordCreateTime the value for order_record.order_record_create_time
     *
     * @mbg.generated
     */
    public void setOrderRecordCreateTime(Date orderRecordCreateTime) {
        this.orderRecordCreateTime = orderRecordCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_record.order_record_update_time
     *
     * @return the value of order_record.order_record_update_time
     *
     * @mbg.generated
     */
    public Date getOrderRecordUpdateTime() {
        return orderRecordUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_record.order_record_update_time
     *
     * @param orderRecordUpdateTime the value for order_record.order_record_update_time
     *
     * @mbg.generated
     */
    public void setOrderRecordUpdateTime(Date orderRecordUpdateTime) {
        this.orderRecordUpdateTime = orderRecordUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_record.order_record_pay_status
     *
     * @return the value of order_record.order_record_pay_status
     *
     * @mbg.generated
     */
    public Byte getOrderRecordPayStatus() {
        return orderRecordPayStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_record.order_record_pay_status
     *
     * @param orderRecordPayStatus the value for order_record.order_record_pay_status
     *
     * @mbg.generated
     */
    public void setOrderRecordPayStatus(Byte orderRecordPayStatus) {
        this.orderRecordPayStatus = orderRecordPayStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_record.order_record_status
     *
     * @return the value of order_record.order_record_status
     *
     * @mbg.generated
     */
    public Byte getOrderRecordStatus() {
        return orderRecordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_record.order_record_status
     *
     * @param orderRecordStatus the value for order_record.order_record_status
     *
     * @mbg.generated
     */
    public void setOrderRecordStatus(Byte orderRecordStatus) {
        this.orderRecordStatus = orderRecordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_record.order_record_user_id
     *
     * @return the value of order_record.order_record_user_id
     *
     * @mbg.generated
     */
    public String getOrderRecordUserId() {
        return orderRecordUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_record.order_record_user_id
     *
     * @param orderRecordUserId the value for order_record.order_record_user_id
     *
     * @mbg.generated
     */
    public void setOrderRecordUserId(String orderRecordUserId) {
        this.orderRecordUserId = orderRecordUserId == null ? null : orderRecordUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_record.order_record_pay_channel
     *
     * @return the value of order_record.order_record_pay_channel
     *
     * @mbg.generated
     */
    public Byte getOrderRecordPayChannel() {
        return orderRecordPayChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_record.order_record_pay_channel
     *
     * @param orderRecordPayChannel the value for order_record.order_record_pay_channel
     *
     * @mbg.generated
     */
    public void setOrderRecordPayChannel(Byte orderRecordPayChannel) {
        this.orderRecordPayChannel = orderRecordPayChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_record.order_record_user_name
     *
     * @return the value of order_record.order_record_user_name
     *
     * @mbg.generated
     */
    public String getOrderRecordUserName() {
        return orderRecordUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_record.order_record_user_name
     *
     * @param orderRecordUserName the value for order_record.order_record_user_name
     *
     * @mbg.generated
     */
    public void setOrderRecordUserName(String orderRecordUserName) {
        this.orderRecordUserName = orderRecordUserName == null ? null : orderRecordUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_record.order_record_return_url
     *
     * @return the value of order_record.order_record_return_url
     *
     * @mbg.generated
     */
    public String getOrderRecordReturnUrl() {
        return orderRecordReturnUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_record.order_record_return_url
     *
     * @param orderRecordReturnUrl the value for order_record.order_record_return_url
     *
     * @mbg.generated
     */
    public void setOrderRecordReturnUrl(String orderRecordReturnUrl) {
        this.orderRecordReturnUrl = orderRecordReturnUrl == null ? null : orderRecordReturnUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_record.order_record_notify_url
     *
     * @return the value of order_record.order_record_notify_url
     *
     * @mbg.generated
     */
    public String getOrderRecordNotifyUrl() {
        return orderRecordNotifyUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_record.order_record_notify_url
     *
     * @param orderRecordNotifyUrl the value for order_record.order_record_notify_url
     *
     * @mbg.generated
     */
    public void setOrderRecordNotifyUrl(String orderRecordNotifyUrl) {
        this.orderRecordNotifyUrl = orderRecordNotifyUrl == null ? null : orderRecordNotifyUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_record.order_record_notify_result
     *
     * @return the value of order_record.order_record_notify_result
     *
     * @mbg.generated
     */
    public Byte getOrderRecordNotifyResult() {
        return orderRecordNotifyResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_record.order_record_notify_result
     *
     * @param orderRecordNotifyResult the value for order_record.order_record_notify_result
     *
     * @mbg.generated
     */
    public void setOrderRecordNotifyResult(Byte orderRecordNotifyResult) {
        this.orderRecordNotifyResult = orderRecordNotifyResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_record.order_record_notify_time
     *
     * @return the value of order_record.order_record_notify_time
     *
     * @mbg.generated
     */
    public Byte getOrderRecordNotifyTime() {
        return orderRecordNotifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_record.order_record_notify_time
     *
     * @param orderRecordNotifyTime the value for order_record.order_record_notify_time
     *
     * @mbg.generated
     */
    public void setOrderRecordNotifyTime(Byte orderRecordNotifyTime) {
        this.orderRecordNotifyTime = orderRecordNotifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_record.trade_no
     *
     * @return the value of order_record.trade_no
     *
     * @mbg.generated
     */
    public String getTradeNo() {
        return tradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_record.trade_no
     *
     * @param tradeNo the value for order_record.trade_no
     *
     * @mbg.generated
     */
    public void setTradeNo(String tradeNo) {
        this.tradeNo = tradeNo == null ? null : tradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_record.buyer_email
     *
     * @return the value of order_record.buyer_email
     *
     * @mbg.generated
     */
    public String getBuyerEmail() {
        return buyerEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_record.buyer_email
     *
     * @param buyerEmail the value for order_record.buyer_email
     *
     * @mbg.generated
     */
    public void setBuyerEmail(String buyerEmail) {
        this.buyerEmail = buyerEmail == null ? null : buyerEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_record.notify_time
     *
     * @return the value of order_record.notify_time
     *
     * @mbg.generated
     */
    public Date getNotifyTime() {
        return notifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_record.notify_time
     *
     * @param notifyTime the value for order_record.notify_time
     *
     * @mbg.generated
     */
    public void setNotifyTime(Date notifyTime) {
        this.notifyTime = notifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_record.buyer_id
     *
     * @return the value of order_record.buyer_id
     *
     * @mbg.generated
     */
    public String getBuyerId() {
        return buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_record.buyer_id
     *
     * @param buyerId the value for order_record.buyer_id
     *
     * @mbg.generated
     */
    public void setBuyerId(String buyerId) {
        this.buyerId = buyerId == null ? null : buyerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_record.total_fee
     *
     * @return the value of order_record.total_fee
     *
     * @mbg.generated
     */
    public Double getTotalFee() {
        return totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_record.total_fee
     *
     * @param totalFee the value for order_record.total_fee
     *
     * @mbg.generated
     */
    public void setTotalFee(Double totalFee) {
        this.totalFee = totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_record.trade_status
     *
     * @return the value of order_record.trade_status
     *
     * @mbg.generated
     */
    public String getTradeStatus() {
        return tradeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_record.trade_status
     *
     * @param tradeStatus the value for order_record.trade_status
     *
     * @mbg.generated
     */
    public void setTradeStatus(String tradeStatus) {
        this.tradeStatus = tradeStatus == null ? null : tradeStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_record.order_record_order_detail
     *
     * @return the value of order_record.order_record_order_detail
     *
     * @mbg.generated
     */
    public String getOrderRecordOrderDetail() {
        return orderRecordOrderDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_record.order_record_order_detail
     *
     * @param orderRecordOrderDetail the value for order_record.order_record_order_detail
     *
     * @mbg.generated
     */
    public void setOrderRecordOrderDetail(String orderRecordOrderDetail) {
        this.orderRecordOrderDetail = orderRecordOrderDetail == null ? null : orderRecordOrderDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        OrderRecord other = (OrderRecord) that;
        return (this.getOrderRecordId() == null ? other.getOrderRecordId() == null : this.getOrderRecordId().equals(other.getOrderRecordId()))
            && (this.getAppId() == null ? other.getAppId() == null : this.getAppId().equals(other.getAppId()))
            && (this.getOrderRecordOrderId() == null ? other.getOrderRecordOrderId() == null : this.getOrderRecordOrderId().equals(other.getOrderRecordOrderId()))
            && (this.getOrderRecordTotalPrice() == null ? other.getOrderRecordTotalPrice() == null : this.getOrderRecordTotalPrice().equals(other.getOrderRecordTotalPrice()))
            && (this.getOrderRecordCreateTime() == null ? other.getOrderRecordCreateTime() == null : this.getOrderRecordCreateTime().equals(other.getOrderRecordCreateTime()))
            && (this.getOrderRecordUpdateTime() == null ? other.getOrderRecordUpdateTime() == null : this.getOrderRecordUpdateTime().equals(other.getOrderRecordUpdateTime()))
            && (this.getOrderRecordPayStatus() == null ? other.getOrderRecordPayStatus() == null : this.getOrderRecordPayStatus().equals(other.getOrderRecordPayStatus()))
            && (this.getOrderRecordStatus() == null ? other.getOrderRecordStatus() == null : this.getOrderRecordStatus().equals(other.getOrderRecordStatus()))
            && (this.getOrderRecordUserId() == null ? other.getOrderRecordUserId() == null : this.getOrderRecordUserId().equals(other.getOrderRecordUserId()))
            && (this.getOrderRecordPayChannel() == null ? other.getOrderRecordPayChannel() == null : this.getOrderRecordPayChannel().equals(other.getOrderRecordPayChannel()))
            && (this.getOrderRecordUserName() == null ? other.getOrderRecordUserName() == null : this.getOrderRecordUserName().equals(other.getOrderRecordUserName()))
            && (this.getOrderRecordReturnUrl() == null ? other.getOrderRecordReturnUrl() == null : this.getOrderRecordReturnUrl().equals(other.getOrderRecordReturnUrl()))
            && (this.getOrderRecordNotifyUrl() == null ? other.getOrderRecordNotifyUrl() == null : this.getOrderRecordNotifyUrl().equals(other.getOrderRecordNotifyUrl()))
            && (this.getOrderRecordNotifyResult() == null ? other.getOrderRecordNotifyResult() == null : this.getOrderRecordNotifyResult().equals(other.getOrderRecordNotifyResult()))
            && (this.getOrderRecordNotifyTime() == null ? other.getOrderRecordNotifyTime() == null : this.getOrderRecordNotifyTime().equals(other.getOrderRecordNotifyTime()))
            && (this.getTradeNo() == null ? other.getTradeNo() == null : this.getTradeNo().equals(other.getTradeNo()))
            && (this.getBuyerEmail() == null ? other.getBuyerEmail() == null : this.getBuyerEmail().equals(other.getBuyerEmail()))
            && (this.getNotifyTime() == null ? other.getNotifyTime() == null : this.getNotifyTime().equals(other.getNotifyTime()))
            && (this.getBuyerId() == null ? other.getBuyerId() == null : this.getBuyerId().equals(other.getBuyerId()))
            && (this.getTotalFee() == null ? other.getTotalFee() == null : this.getTotalFee().equals(other.getTotalFee()))
            && (this.getTradeStatus() == null ? other.getTradeStatus() == null : this.getTradeStatus().equals(other.getTradeStatus()))
            && (this.getOrderRecordOrderDetail() == null ? other.getOrderRecordOrderDetail() == null : this.getOrderRecordOrderDetail().equals(other.getOrderRecordOrderDetail()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getOrderRecordId() == null) ? 0 : getOrderRecordId().hashCode());
        result = prime * result + ((getAppId() == null) ? 0 : getAppId().hashCode());
        result = prime * result + ((getOrderRecordOrderId() == null) ? 0 : getOrderRecordOrderId().hashCode());
        result = prime * result + ((getOrderRecordTotalPrice() == null) ? 0 : getOrderRecordTotalPrice().hashCode());
        result = prime * result + ((getOrderRecordCreateTime() == null) ? 0 : getOrderRecordCreateTime().hashCode());
        result = prime * result + ((getOrderRecordUpdateTime() == null) ? 0 : getOrderRecordUpdateTime().hashCode());
        result = prime * result + ((getOrderRecordPayStatus() == null) ? 0 : getOrderRecordPayStatus().hashCode());
        result = prime * result + ((getOrderRecordStatus() == null) ? 0 : getOrderRecordStatus().hashCode());
        result = prime * result + ((getOrderRecordUserId() == null) ? 0 : getOrderRecordUserId().hashCode());
        result = prime * result + ((getOrderRecordPayChannel() == null) ? 0 : getOrderRecordPayChannel().hashCode());
        result = prime * result + ((getOrderRecordUserName() == null) ? 0 : getOrderRecordUserName().hashCode());
        result = prime * result + ((getOrderRecordReturnUrl() == null) ? 0 : getOrderRecordReturnUrl().hashCode());
        result = prime * result + ((getOrderRecordNotifyUrl() == null) ? 0 : getOrderRecordNotifyUrl().hashCode());
        result = prime * result + ((getOrderRecordNotifyResult() == null) ? 0 : getOrderRecordNotifyResult().hashCode());
        result = prime * result + ((getOrderRecordNotifyTime() == null) ? 0 : getOrderRecordNotifyTime().hashCode());
        result = prime * result + ((getTradeNo() == null) ? 0 : getTradeNo().hashCode());
        result = prime * result + ((getBuyerEmail() == null) ? 0 : getBuyerEmail().hashCode());
        result = prime * result + ((getNotifyTime() == null) ? 0 : getNotifyTime().hashCode());
        result = prime * result + ((getBuyerId() == null) ? 0 : getBuyerId().hashCode());
        result = prime * result + ((getTotalFee() == null) ? 0 : getTotalFee().hashCode());
        result = prime * result + ((getTradeStatus() == null) ? 0 : getTradeStatus().hashCode());
        result = prime * result + ((getOrderRecordOrderDetail() == null) ? 0 : getOrderRecordOrderDetail().hashCode());
        return result;
    }
}