package org.epay.model.base;

import java.util.ArrayList;
import java.util.List;

public class OrderGoodsCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_goods
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_goods
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_goods
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_goods
     *
     * @mbg.generated
     */
    protected int limitStart = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_goods
     *
     * @mbg.generated
     */
    protected int pageSize = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods
     *
     * @mbg.generated
     */
    public OrderGoodsCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods
     *
     * @mbg.generated
     */
    public void setLimitStart(int limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods
     *
     * @mbg.generated
     */
    public int getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods
     *
     * @mbg.generated
     */
    public void setPageSize(int pageSize) {
        this.pageSize=pageSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods
     *
     * @mbg.generated
     */
    public int getPageSize() {
        return pageSize;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_goods
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOrderGoodsIdIsNull() {
            addCriterion("order_goods_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsIdIsNotNull() {
            addCriterion("order_goods_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsIdEqualTo(String value) {
            addCriterion("order_goods_id =", value, "orderGoodsId");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsIdNotEqualTo(String value) {
            addCriterion("order_goods_id <>", value, "orderGoodsId");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsIdGreaterThan(String value) {
            addCriterion("order_goods_id >", value, "orderGoodsId");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsIdGreaterThanOrEqualTo(String value) {
            addCriterion("order_goods_id >=", value, "orderGoodsId");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsIdLessThan(String value) {
            addCriterion("order_goods_id <", value, "orderGoodsId");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsIdLessThanOrEqualTo(String value) {
            addCriterion("order_goods_id <=", value, "orderGoodsId");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsIdLike(String value) {
            addCriterion("order_goods_id like", value, "orderGoodsId");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsIdNotLike(String value) {
            addCriterion("order_goods_id not like", value, "orderGoodsId");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsIdIn(List<String> values) {
            addCriterion("order_goods_id in", values, "orderGoodsId");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsIdNotIn(List<String> values) {
            addCriterion("order_goods_id not in", values, "orderGoodsId");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsIdBetween(String value1, String value2) {
            addCriterion("order_goods_id between", value1, value2, "orderGoodsId");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsIdNotBetween(String value1, String value2) {
            addCriterion("order_goods_id not between", value1, value2, "orderGoodsId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordIdIsNull() {
            addCriterion("order_record_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderRecordIdIsNotNull() {
            addCriterion("order_record_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderRecordIdEqualTo(String value) {
            addCriterion("order_record_id =", value, "orderRecordId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordIdNotEqualTo(String value) {
            addCriterion("order_record_id <>", value, "orderRecordId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordIdGreaterThan(String value) {
            addCriterion("order_record_id >", value, "orderRecordId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordIdGreaterThanOrEqualTo(String value) {
            addCriterion("order_record_id >=", value, "orderRecordId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordIdLessThan(String value) {
            addCriterion("order_record_id <", value, "orderRecordId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordIdLessThanOrEqualTo(String value) {
            addCriterion("order_record_id <=", value, "orderRecordId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordIdLike(String value) {
            addCriterion("order_record_id like", value, "orderRecordId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordIdNotLike(String value) {
            addCriterion("order_record_id not like", value, "orderRecordId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordIdIn(List<String> values) {
            addCriterion("order_record_id in", values, "orderRecordId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordIdNotIn(List<String> values) {
            addCriterion("order_record_id not in", values, "orderRecordId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordIdBetween(String value1, String value2) {
            addCriterion("order_record_id between", value1, value2, "orderRecordId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordIdNotBetween(String value1, String value2) {
            addCriterion("order_record_id not between", value1, value2, "orderRecordId");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsGoodsIdIsNull() {
            addCriterion("order_goods_goods_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsGoodsIdIsNotNull() {
            addCriterion("order_goods_goods_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsGoodsIdEqualTo(String value) {
            addCriterion("order_goods_goods_id =", value, "orderGoodsGoodsId");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsGoodsIdNotEqualTo(String value) {
            addCriterion("order_goods_goods_id <>", value, "orderGoodsGoodsId");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsGoodsIdGreaterThan(String value) {
            addCriterion("order_goods_goods_id >", value, "orderGoodsGoodsId");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsGoodsIdGreaterThanOrEqualTo(String value) {
            addCriterion("order_goods_goods_id >=", value, "orderGoodsGoodsId");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsGoodsIdLessThan(String value) {
            addCriterion("order_goods_goods_id <", value, "orderGoodsGoodsId");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsGoodsIdLessThanOrEqualTo(String value) {
            addCriterion("order_goods_goods_id <=", value, "orderGoodsGoodsId");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsGoodsIdLike(String value) {
            addCriterion("order_goods_goods_id like", value, "orderGoodsGoodsId");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsGoodsIdNotLike(String value) {
            addCriterion("order_goods_goods_id not like", value, "orderGoodsGoodsId");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsGoodsIdIn(List<String> values) {
            addCriterion("order_goods_goods_id in", values, "orderGoodsGoodsId");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsGoodsIdNotIn(List<String> values) {
            addCriterion("order_goods_goods_id not in", values, "orderGoodsGoodsId");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsGoodsIdBetween(String value1, String value2) {
            addCriterion("order_goods_goods_id between", value1, value2, "orderGoodsGoodsId");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsGoodsIdNotBetween(String value1, String value2) {
            addCriterion("order_goods_goods_id not between", value1, value2, "orderGoodsGoodsId");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsNameIsNull() {
            addCriterion("order_goods_name is null");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsNameIsNotNull() {
            addCriterion("order_goods_name is not null");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsNameEqualTo(String value) {
            addCriterion("order_goods_name =", value, "orderGoodsName");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsNameNotEqualTo(String value) {
            addCriterion("order_goods_name <>", value, "orderGoodsName");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsNameGreaterThan(String value) {
            addCriterion("order_goods_name >", value, "orderGoodsName");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsNameGreaterThanOrEqualTo(String value) {
            addCriterion("order_goods_name >=", value, "orderGoodsName");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsNameLessThan(String value) {
            addCriterion("order_goods_name <", value, "orderGoodsName");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsNameLessThanOrEqualTo(String value) {
            addCriterion("order_goods_name <=", value, "orderGoodsName");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsNameLike(String value) {
            addCriterion("order_goods_name like", value, "orderGoodsName");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsNameNotLike(String value) {
            addCriterion("order_goods_name not like", value, "orderGoodsName");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsNameIn(List<String> values) {
            addCriterion("order_goods_name in", values, "orderGoodsName");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsNameNotIn(List<String> values) {
            addCriterion("order_goods_name not in", values, "orderGoodsName");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsNameBetween(String value1, String value2) {
            addCriterion("order_goods_name between", value1, value2, "orderGoodsName");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsNameNotBetween(String value1, String value2) {
            addCriterion("order_goods_name not between", value1, value2, "orderGoodsName");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsPriceIsNull() {
            addCriterion("order_goods_price is null");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsPriceIsNotNull() {
            addCriterion("order_goods_price is not null");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsPriceEqualTo(Double value) {
            addCriterion("order_goods_price =", value, "orderGoodsPrice");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsPriceNotEqualTo(Double value) {
            addCriterion("order_goods_price <>", value, "orderGoodsPrice");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsPriceGreaterThan(Double value) {
            addCriterion("order_goods_price >", value, "orderGoodsPrice");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("order_goods_price >=", value, "orderGoodsPrice");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsPriceLessThan(Double value) {
            addCriterion("order_goods_price <", value, "orderGoodsPrice");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsPriceLessThanOrEqualTo(Double value) {
            addCriterion("order_goods_price <=", value, "orderGoodsPrice");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsPriceIn(List<Double> values) {
            addCriterion("order_goods_price in", values, "orderGoodsPrice");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsPriceNotIn(List<Double> values) {
            addCriterion("order_goods_price not in", values, "orderGoodsPrice");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsPriceBetween(Double value1, Double value2) {
            addCriterion("order_goods_price between", value1, value2, "orderGoodsPrice");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsPriceNotBetween(Double value1, Double value2) {
            addCriterion("order_goods_price not between", value1, value2, "orderGoodsPrice");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsNumberIsNull() {
            addCriterion("order_goods_number is null");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsNumberIsNotNull() {
            addCriterion("order_goods_number is not null");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsNumberEqualTo(Integer value) {
            addCriterion("order_goods_number =", value, "orderGoodsNumber");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsNumberNotEqualTo(Integer value) {
            addCriterion("order_goods_number <>", value, "orderGoodsNumber");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsNumberGreaterThan(Integer value) {
            addCriterion("order_goods_number >", value, "orderGoodsNumber");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_goods_number >=", value, "orderGoodsNumber");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsNumberLessThan(Integer value) {
            addCriterion("order_goods_number <", value, "orderGoodsNumber");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsNumberLessThanOrEqualTo(Integer value) {
            addCriterion("order_goods_number <=", value, "orderGoodsNumber");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsNumberIn(List<Integer> values) {
            addCriterion("order_goods_number in", values, "orderGoodsNumber");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsNumberNotIn(List<Integer> values) {
            addCriterion("order_goods_number not in", values, "orderGoodsNumber");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsNumberBetween(Integer value1, Integer value2) {
            addCriterion("order_goods_number between", value1, value2, "orderGoodsNumber");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("order_goods_number not between", value1, value2, "orderGoodsNumber");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsDetailIsNull() {
            addCriterion("order_goods_detail is null");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsDetailIsNotNull() {
            addCriterion("order_goods_detail is not null");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsDetailEqualTo(String value) {
            addCriterion("order_goods_detail =", value, "orderGoodsDetail");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsDetailNotEqualTo(String value) {
            addCriterion("order_goods_detail <>", value, "orderGoodsDetail");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsDetailGreaterThan(String value) {
            addCriterion("order_goods_detail >", value, "orderGoodsDetail");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsDetailGreaterThanOrEqualTo(String value) {
            addCriterion("order_goods_detail >=", value, "orderGoodsDetail");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsDetailLessThan(String value) {
            addCriterion("order_goods_detail <", value, "orderGoodsDetail");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsDetailLessThanOrEqualTo(String value) {
            addCriterion("order_goods_detail <=", value, "orderGoodsDetail");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsDetailLike(String value) {
            addCriterion("order_goods_detail like", value, "orderGoodsDetail");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsDetailNotLike(String value) {
            addCriterion("order_goods_detail not like", value, "orderGoodsDetail");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsDetailIn(List<String> values) {
            addCriterion("order_goods_detail in", values, "orderGoodsDetail");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsDetailNotIn(List<String> values) {
            addCriterion("order_goods_detail not in", values, "orderGoodsDetail");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsDetailBetween(String value1, String value2) {
            addCriterion("order_goods_detail between", value1, value2, "orderGoodsDetail");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsDetailNotBetween(String value1, String value2) {
            addCriterion("order_goods_detail not between", value1, value2, "orderGoodsDetail");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsUrlIsNull() {
            addCriterion("order_goods_url is null");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsUrlIsNotNull() {
            addCriterion("order_goods_url is not null");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsUrlEqualTo(String value) {
            addCriterion("order_goods_url =", value, "orderGoodsUrl");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsUrlNotEqualTo(String value) {
            addCriterion("order_goods_url <>", value, "orderGoodsUrl");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsUrlGreaterThan(String value) {
            addCriterion("order_goods_url >", value, "orderGoodsUrl");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsUrlGreaterThanOrEqualTo(String value) {
            addCriterion("order_goods_url >=", value, "orderGoodsUrl");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsUrlLessThan(String value) {
            addCriterion("order_goods_url <", value, "orderGoodsUrl");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsUrlLessThanOrEqualTo(String value) {
            addCriterion("order_goods_url <=", value, "orderGoodsUrl");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsUrlLike(String value) {
            addCriterion("order_goods_url like", value, "orderGoodsUrl");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsUrlNotLike(String value) {
            addCriterion("order_goods_url not like", value, "orderGoodsUrl");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsUrlIn(List<String> values) {
            addCriterion("order_goods_url in", values, "orderGoodsUrl");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsUrlNotIn(List<String> values) {
            addCriterion("order_goods_url not in", values, "orderGoodsUrl");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsUrlBetween(String value1, String value2) {
            addCriterion("order_goods_url between", value1, value2, "orderGoodsUrl");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsUrlNotBetween(String value1, String value2) {
            addCriterion("order_goods_url not between", value1, value2, "orderGoodsUrl");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsIdLikeInsensitive(String value) {
            addCriterion("upper(order_goods_id) like", value.toUpperCase(), "orderGoodsId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordIdLikeInsensitive(String value) {
            addCriterion("upper(order_record_id) like", value.toUpperCase(), "orderRecordId");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsGoodsIdLikeInsensitive(String value) {
            addCriterion("upper(order_goods_goods_id) like", value.toUpperCase(), "orderGoodsGoodsId");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsNameLikeInsensitive(String value) {
            addCriterion("upper(order_goods_name) like", value.toUpperCase(), "orderGoodsName");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsDetailLikeInsensitive(String value) {
            addCriterion("upper(order_goods_detail) like", value.toUpperCase(), "orderGoodsDetail");
            return (Criteria) this;
        }

        public Criteria andOrderGoodsUrlLikeInsensitive(String value) {
            addCriterion("upper(order_goods_url) like", value.toUpperCase(), "orderGoodsUrl");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_goods
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_goods
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}