package org.epay.model.base;

import java.io.Serializable;

public class OrderGoods implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.order_goods_id
     *
     * @mbg.generated
     */
    private String orderGoodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.order_record_id
     *
     * @mbg.generated
     */
    private String orderRecordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.order_goods_goods_id
     *
     * @mbg.generated
     */
    private String orderGoodsGoodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.order_goods_name
     *
     * @mbg.generated
     */
    private String orderGoodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.order_goods_price
     *
     * @mbg.generated
     */
    private Double orderGoodsPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.order_goods_number
     *
     * @mbg.generated
     */
    private Integer orderGoodsNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.order_goods_detail
     *
     * @mbg.generated
     */
    private String orderGoodsDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.order_goods_url
     *
     * @mbg.generated
     */
    private String orderGoodsUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_goods
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.order_goods_id
     *
     * @return the value of order_goods.order_goods_id
     *
     * @mbg.generated
     */
    public String getOrderGoodsId() {
        return orderGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.order_goods_id
     *
     * @param orderGoodsId the value for order_goods.order_goods_id
     *
     * @mbg.generated
     */
    public void setOrderGoodsId(String orderGoodsId) {
        this.orderGoodsId = orderGoodsId == null ? null : orderGoodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.order_record_id
     *
     * @return the value of order_goods.order_record_id
     *
     * @mbg.generated
     */
    public String getOrderRecordId() {
        return orderRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.order_record_id
     *
     * @param orderRecordId the value for order_goods.order_record_id
     *
     * @mbg.generated
     */
    public void setOrderRecordId(String orderRecordId) {
        this.orderRecordId = orderRecordId == null ? null : orderRecordId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.order_goods_goods_id
     *
     * @return the value of order_goods.order_goods_goods_id
     *
     * @mbg.generated
     */
    public String getOrderGoodsGoodsId() {
        return orderGoodsGoodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.order_goods_goods_id
     *
     * @param orderGoodsGoodsId the value for order_goods.order_goods_goods_id
     *
     * @mbg.generated
     */
    public void setOrderGoodsGoodsId(String orderGoodsGoodsId) {
        this.orderGoodsGoodsId = orderGoodsGoodsId == null ? null : orderGoodsGoodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.order_goods_name
     *
     * @return the value of order_goods.order_goods_name
     *
     * @mbg.generated
     */
    public String getOrderGoodsName() {
        return orderGoodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.order_goods_name
     *
     * @param orderGoodsName the value for order_goods.order_goods_name
     *
     * @mbg.generated
     */
    public void setOrderGoodsName(String orderGoodsName) {
        this.orderGoodsName = orderGoodsName == null ? null : orderGoodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.order_goods_price
     *
     * @return the value of order_goods.order_goods_price
     *
     * @mbg.generated
     */
    public Double getOrderGoodsPrice() {
        return orderGoodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.order_goods_price
     *
     * @param orderGoodsPrice the value for order_goods.order_goods_price
     *
     * @mbg.generated
     */
    public void setOrderGoodsPrice(Double orderGoodsPrice) {
        this.orderGoodsPrice = orderGoodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.order_goods_number
     *
     * @return the value of order_goods.order_goods_number
     *
     * @mbg.generated
     */
    public Integer getOrderGoodsNumber() {
        return orderGoodsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.order_goods_number
     *
     * @param orderGoodsNumber the value for order_goods.order_goods_number
     *
     * @mbg.generated
     */
    public void setOrderGoodsNumber(Integer orderGoodsNumber) {
        this.orderGoodsNumber = orderGoodsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.order_goods_detail
     *
     * @return the value of order_goods.order_goods_detail
     *
     * @mbg.generated
     */
    public String getOrderGoodsDetail() {
        return orderGoodsDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.order_goods_detail
     *
     * @param orderGoodsDetail the value for order_goods.order_goods_detail
     *
     * @mbg.generated
     */
    public void setOrderGoodsDetail(String orderGoodsDetail) {
        this.orderGoodsDetail = orderGoodsDetail == null ? null : orderGoodsDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.order_goods_url
     *
     * @return the value of order_goods.order_goods_url
     *
     * @mbg.generated
     */
    public String getOrderGoodsUrl() {
        return orderGoodsUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.order_goods_url
     *
     * @param orderGoodsUrl the value for order_goods.order_goods_url
     *
     * @mbg.generated
     */
    public void setOrderGoodsUrl(String orderGoodsUrl) {
        this.orderGoodsUrl = orderGoodsUrl == null ? null : orderGoodsUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        OrderGoods other = (OrderGoods) that;
        return (this.getOrderGoodsId() == null ? other.getOrderGoodsId() == null : this.getOrderGoodsId().equals(other.getOrderGoodsId()))
            && (this.getOrderRecordId() == null ? other.getOrderRecordId() == null : this.getOrderRecordId().equals(other.getOrderRecordId()))
            && (this.getOrderGoodsGoodsId() == null ? other.getOrderGoodsGoodsId() == null : this.getOrderGoodsGoodsId().equals(other.getOrderGoodsGoodsId()))
            && (this.getOrderGoodsName() == null ? other.getOrderGoodsName() == null : this.getOrderGoodsName().equals(other.getOrderGoodsName()))
            && (this.getOrderGoodsPrice() == null ? other.getOrderGoodsPrice() == null : this.getOrderGoodsPrice().equals(other.getOrderGoodsPrice()))
            && (this.getOrderGoodsNumber() == null ? other.getOrderGoodsNumber() == null : this.getOrderGoodsNumber().equals(other.getOrderGoodsNumber()))
            && (this.getOrderGoodsDetail() == null ? other.getOrderGoodsDetail() == null : this.getOrderGoodsDetail().equals(other.getOrderGoodsDetail()))
            && (this.getOrderGoodsUrl() == null ? other.getOrderGoodsUrl() == null : this.getOrderGoodsUrl().equals(other.getOrderGoodsUrl()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_goods
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getOrderGoodsId() == null) ? 0 : getOrderGoodsId().hashCode());
        result = prime * result + ((getOrderRecordId() == null) ? 0 : getOrderRecordId().hashCode());
        result = prime * result + ((getOrderGoodsGoodsId() == null) ? 0 : getOrderGoodsGoodsId().hashCode());
        result = prime * result + ((getOrderGoodsName() == null) ? 0 : getOrderGoodsName().hashCode());
        result = prime * result + ((getOrderGoodsPrice() == null) ? 0 : getOrderGoodsPrice().hashCode());
        result = prime * result + ((getOrderGoodsNumber() == null) ? 0 : getOrderGoodsNumber().hashCode());
        result = prime * result + ((getOrderGoodsDetail() == null) ? 0 : getOrderGoodsDetail().hashCode());
        result = prime * result + ((getOrderGoodsUrl() == null) ? 0 : getOrderGoodsUrl().hashCode());
        return result;
    }
}