package org.epay.model.base;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PayNotifyLogCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pay_notify_log
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pay_notify_log
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pay_notify_log
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pay_notify_log
     *
     * @mbg.generated
     */
    protected int limitStart = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pay_notify_log
     *
     * @mbg.generated
     */
    protected int pageSize = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_notify_log
     *
     * @mbg.generated
     */
    public PayNotifyLogCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_notify_log
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_notify_log
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_notify_log
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_notify_log
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_notify_log
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_notify_log
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_notify_log
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_notify_log
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_notify_log
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_notify_log
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_notify_log
     *
     * @mbg.generated
     */
    public void setLimitStart(int limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_notify_log
     *
     * @mbg.generated
     */
    public int getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_notify_log
     *
     * @mbg.generated
     */
    public void setPageSize(int pageSize) {
        this.pageSize=pageSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_notify_log
     *
     * @mbg.generated
     */
    public int getPageSize() {
        return pageSize;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pay_notify_log
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPayNotiftyLogIdIsNull() {
            addCriterion("pay_notifty_log_id is null");
            return (Criteria) this;
        }

        public Criteria andPayNotiftyLogIdIsNotNull() {
            addCriterion("pay_notifty_log_id is not null");
            return (Criteria) this;
        }

        public Criteria andPayNotiftyLogIdEqualTo(String value) {
            addCriterion("pay_notifty_log_id =", value, "payNotiftyLogId");
            return (Criteria) this;
        }

        public Criteria andPayNotiftyLogIdNotEqualTo(String value) {
            addCriterion("pay_notifty_log_id <>", value, "payNotiftyLogId");
            return (Criteria) this;
        }

        public Criteria andPayNotiftyLogIdGreaterThan(String value) {
            addCriterion("pay_notifty_log_id >", value, "payNotiftyLogId");
            return (Criteria) this;
        }

        public Criteria andPayNotiftyLogIdGreaterThanOrEqualTo(String value) {
            addCriterion("pay_notifty_log_id >=", value, "payNotiftyLogId");
            return (Criteria) this;
        }

        public Criteria andPayNotiftyLogIdLessThan(String value) {
            addCriterion("pay_notifty_log_id <", value, "payNotiftyLogId");
            return (Criteria) this;
        }

        public Criteria andPayNotiftyLogIdLessThanOrEqualTo(String value) {
            addCriterion("pay_notifty_log_id <=", value, "payNotiftyLogId");
            return (Criteria) this;
        }

        public Criteria andPayNotiftyLogIdLike(String value) {
            addCriterion("pay_notifty_log_id like", value, "payNotiftyLogId");
            return (Criteria) this;
        }

        public Criteria andPayNotiftyLogIdNotLike(String value) {
            addCriterion("pay_notifty_log_id not like", value, "payNotiftyLogId");
            return (Criteria) this;
        }

        public Criteria andPayNotiftyLogIdIn(List<String> values) {
            addCriterion("pay_notifty_log_id in", values, "payNotiftyLogId");
            return (Criteria) this;
        }

        public Criteria andPayNotiftyLogIdNotIn(List<String> values) {
            addCriterion("pay_notifty_log_id not in", values, "payNotiftyLogId");
            return (Criteria) this;
        }

        public Criteria andPayNotiftyLogIdBetween(String value1, String value2) {
            addCriterion("pay_notifty_log_id between", value1, value2, "payNotiftyLogId");
            return (Criteria) this;
        }

        public Criteria andPayNotiftyLogIdNotBetween(String value1, String value2) {
            addCriterion("pay_notifty_log_id not between", value1, value2, "payNotiftyLogId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordIdIsNull() {
            addCriterion("order_record_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderRecordIdIsNotNull() {
            addCriterion("order_record_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderRecordIdEqualTo(String value) {
            addCriterion("order_record_id =", value, "orderRecordId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordIdNotEqualTo(String value) {
            addCriterion("order_record_id <>", value, "orderRecordId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordIdGreaterThan(String value) {
            addCriterion("order_record_id >", value, "orderRecordId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordIdGreaterThanOrEqualTo(String value) {
            addCriterion("order_record_id >=", value, "orderRecordId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordIdLessThan(String value) {
            addCriterion("order_record_id <", value, "orderRecordId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordIdLessThanOrEqualTo(String value) {
            addCriterion("order_record_id <=", value, "orderRecordId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordIdLike(String value) {
            addCriterion("order_record_id like", value, "orderRecordId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordIdNotLike(String value) {
            addCriterion("order_record_id not like", value, "orderRecordId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordIdIn(List<String> values) {
            addCriterion("order_record_id in", values, "orderRecordId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordIdNotIn(List<String> values) {
            addCriterion("order_record_id not in", values, "orderRecordId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordIdBetween(String value1, String value2) {
            addCriterion("order_record_id between", value1, value2, "orderRecordId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordIdNotBetween(String value1, String value2) {
            addCriterion("order_record_id not between", value1, value2, "orderRecordId");
            return (Criteria) this;
        }

        public Criteria andPayNotifyCreateTimeIsNull() {
            addCriterion("pay_notify_create_time is null");
            return (Criteria) this;
        }

        public Criteria andPayNotifyCreateTimeIsNotNull() {
            addCriterion("pay_notify_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andPayNotifyCreateTimeEqualTo(Date value) {
            addCriterion("pay_notify_create_time =", value, "payNotifyCreateTime");
            return (Criteria) this;
        }

        public Criteria andPayNotifyCreateTimeNotEqualTo(Date value) {
            addCriterion("pay_notify_create_time <>", value, "payNotifyCreateTime");
            return (Criteria) this;
        }

        public Criteria andPayNotifyCreateTimeGreaterThan(Date value) {
            addCriterion("pay_notify_create_time >", value, "payNotifyCreateTime");
            return (Criteria) this;
        }

        public Criteria andPayNotifyCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("pay_notify_create_time >=", value, "payNotifyCreateTime");
            return (Criteria) this;
        }

        public Criteria andPayNotifyCreateTimeLessThan(Date value) {
            addCriterion("pay_notify_create_time <", value, "payNotifyCreateTime");
            return (Criteria) this;
        }

        public Criteria andPayNotifyCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("pay_notify_create_time <=", value, "payNotifyCreateTime");
            return (Criteria) this;
        }

        public Criteria andPayNotifyCreateTimeIn(List<Date> values) {
            addCriterion("pay_notify_create_time in", values, "payNotifyCreateTime");
            return (Criteria) this;
        }

        public Criteria andPayNotifyCreateTimeNotIn(List<Date> values) {
            addCriterion("pay_notify_create_time not in", values, "payNotifyCreateTime");
            return (Criteria) this;
        }

        public Criteria andPayNotifyCreateTimeBetween(Date value1, Date value2) {
            addCriterion("pay_notify_create_time between", value1, value2, "payNotifyCreateTime");
            return (Criteria) this;
        }

        public Criteria andPayNotifyCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("pay_notify_create_time not between", value1, value2, "payNotifyCreateTime");
            return (Criteria) this;
        }

        public Criteria andPayNotiftyLogIdLikeInsensitive(String value) {
            addCriterion("upper(pay_notifty_log_id) like", value.toUpperCase(), "payNotiftyLogId");
            return (Criteria) this;
        }

        public Criteria andOrderRecordIdLikeInsensitive(String value) {
            addCriterion("upper(order_record_id) like", value.toUpperCase(), "orderRecordId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pay_notify_log
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pay_notify_log
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}