package org.epay.dao.base;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.epay.model.base.OrderRecord;
import org.epay.model.base.OrderRecordCriteria;

public interface OrderRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbg.generated
     */
    long countByExample(OrderRecordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbg.generated
     */
    int deleteByExample(OrderRecordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String orderRecordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbg.generated
     */
    int insert(OrderRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbg.generated
     */
    int insertSelective(OrderRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbg.generated
     */
    List<OrderRecord> selectByExampleWithBLOBs(OrderRecordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbg.generated
     */
    List<OrderRecord> selectByExample(OrderRecordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbg.generated
     */
    OrderRecord selectByPrimaryKey(String orderRecordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") OrderRecord record, @Param("example") OrderRecordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") OrderRecord record, @Param("example") OrderRecordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") OrderRecord record, @Param("example") OrderRecordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OrderRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(OrderRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OrderRecord record);
}