package dao.dao.ext;

import dao.model.base.OrderRecordCriteria;
import dao.model.ext.OrderRecordExt;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderRecordMapperExt {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbg.generated
     */
    long countByExample(OrderRecordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbg.generated
     */
    int deleteByExample(OrderRecordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String orderRecordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbg.generated
     */
    int insert(OrderRecordExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbg.generated
     */
    int insertSelective(OrderRecordExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbg.generated
     */
    List<OrderRecordExt> selectByExampleWithBLOBs(OrderRecordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbg.generated
     */
    List<OrderRecordExt> selectByExample(OrderRecordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbg.generated
     */
    OrderRecordExt selectByPrimaryKey(String orderRecordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") OrderRecordExt record, @Param("example") OrderRecordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") OrderRecordExt record, @Param("example") OrderRecordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") OrderRecordExt record, @Param("example") OrderRecordCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OrderRecordExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(OrderRecordExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OrderRecordExt record);
}