package dao.dao.base;

import dao.model.base.Notify;
import dao.model.base.NotifyCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NotifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify
     *
     * @mbg.generated
     */
    long countByExample(NotifyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify
     *
     * @mbg.generated
     */
    int deleteByExample(NotifyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String notifyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify
     *
     * @mbg.generated
     */
    int insert(Notify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify
     *
     * @mbg.generated
     */
    int insertSelective(Notify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify
     *
     * @mbg.generated
     */
    List<Notify> selectByExample(NotifyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify
     *
     * @mbg.generated
     */
    Notify selectByPrimaryKey(String notifyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Notify record, @Param("example") NotifyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Notify record, @Param("example") NotifyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Notify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notify
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Notify record);
}