package dao.dao.base;

import dao.model.base.PayNotifyLog;
import dao.model.base.PayNotifyLogCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PayNotifyLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_notify_log
     *
     * @mbg.generated
     */
    long countByExample(PayNotifyLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_notify_log
     *
     * @mbg.generated
     */
    int deleteByExample(PayNotifyLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_notify_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String payNotiftyLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_notify_log
     *
     * @mbg.generated
     */
    int insert(PayNotifyLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_notify_log
     *
     * @mbg.generated
     */
    int insertSelective(PayNotifyLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_notify_log
     *
     * @mbg.generated
     */
    List<PayNotifyLog> selectByExampleWithBLOBs(PayNotifyLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_notify_log
     *
     * @mbg.generated
     */
    List<PayNotifyLog> selectByExample(PayNotifyLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_notify_log
     *
     * @mbg.generated
     */
    PayNotifyLog selectByPrimaryKey(String payNotiftyLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_notify_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PayNotifyLog record, @Param("example") PayNotifyLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_notify_log
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") PayNotifyLog record, @Param("example") PayNotifyLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_notify_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PayNotifyLog record, @Param("example") PayNotifyLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_notify_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PayNotifyLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_notify_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(PayNotifyLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_notify_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PayNotifyLog record);
}